# coding: utf-8

"""
    Requiems API

    Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_entertainment_emoji_name_get200_response import V1EntertainmentEmojiNameGet200Response

class TestV1EntertainmentEmojiNameGet200Response(unittest.TestCase):
    """V1EntertainmentEmojiNameGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1EntertainmentEmojiNameGet200Response:
        """Test V1EntertainmentEmojiNameGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1EntertainmentEmojiNameGet200Response`
        """
        model = V1EntertainmentEmojiNameGet200Response()
        if include_optional:
            return V1EntertainmentEmojiNameGet200Response(
                data = openapi_client.models._v1_entertainment_emoji__name__get_200_response_data._v1_entertainment_emoji__name__get_200_response_data(
                    emoji = '', 
                    name = '', 
                    category = '', 
                    unicode = '', ),
                metadata = openapi_client.models._v1_text_advice_get_200_response_metadata._v1_text_advice_get_200_response_metadata(
                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return V1EntertainmentEmojiNameGet200Response(
        )
        """

    def testV1EntertainmentEmojiNameGet200Response(self):
        """Test V1EntertainmentEmojiNameGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
