# coding: utf-8

"""
    Requiems API

    Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.holidays_api import HolidaysApi


class TestHolidaysApi(unittest.TestCase):
    """HolidaysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HolidaysApi()

    def tearDown(self) -> None:
        pass

    def test_v1_places_holidays_batch_post(self) -> None:
        """Test case for v1_places_holidays_batch_post

        Batch Get Holidays
        """
        pass

    def test_v1_places_holidays_get(self) -> None:
        """Test case for v1_places_holidays_get

        Get Holidays
        """
        pass


if __name__ == '__main__':
    unittest.main()
