# coding: utf-8

"""
    Requiems API

    Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_entertainment_sudoku_batch_post_request import V1EntertainmentSudokuBatchPostRequest

class TestV1EntertainmentSudokuBatchPostRequest(unittest.TestCase):
    """V1EntertainmentSudokuBatchPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1EntertainmentSudokuBatchPostRequest:
        """Test V1EntertainmentSudokuBatchPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1EntertainmentSudokuBatchPostRequest`
        """
        model = V1EntertainmentSudokuBatchPostRequest()
        if include_optional:
            return V1EntertainmentSudokuBatchPostRequest(
                puzzles = ["easy", "medium", "hard"]
            )
        else:
            return V1EntertainmentSudokuBatchPostRequest(
                puzzles = ["easy", "medium", "hard"],
        )
        """

    def testV1EntertainmentSudokuBatchPostRequest(self):
        """Test V1EntertainmentSudokuBatchPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
