/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithSignItemRequestBuilder, WithSignItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/entertainment/horoscope
 */
export interface HoroscopeRequestBuilder extends BaseRequestBuilder<HoroscopeRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.v1.entertainment.horoscope.item collection
     * @param sign Zodiac sign (case-insensitive). Supported values: aries, taurus, gemini, cancer, leo, virgo, libra, scorpio, sagittarius, capricorn, aquarius, pisces
     * @returns {WithSignItemRequestBuilder}
     */
     bySign(sign: string) : WithSignItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const HoroscopeRequestBuilderUriTemplate = "{+baseurl}/v1/entertainment/horoscope";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const HoroscopeRequestBuilderNavigationMetadata: Record<Exclude<keyof HoroscopeRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySign: {
        requestsMetadata: WithSignItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["sign"],
    },
};
/* tslint:enable */
/* eslint-enable */
