/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RandomGetResponse_data}
 */
// @ts-ignore
export function createRandomGetResponse_dataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRandomGetResponse_data;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RandomGetResponse_metadata}
 */
// @ts-ignore
export function createRandomGetResponse_metadataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRandomGetResponse_metadata;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RandomGetResponse}
 */
// @ts-ignore
export function createRandomGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRandomGetResponse;
}
/**
 * The deserialization information for the current model
 * @param RandomGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRandomGetResponse(randomGetResponse: Partial<RandomGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { randomGetResponse.data = n.getObjectValue<RandomGetResponse_data>(createRandomGetResponse_dataFromDiscriminatorValue); },
        "metadata": n => { randomGetResponse.metadata = n.getObjectValue<RandomGetResponse_metadata>(createRandomGetResponse_metadataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param RandomGetResponse_data The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRandomGetResponse_data(randomGetResponse_data: Partial<RandomGetResponse_data> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "author": n => { randomGetResponse_data.author = n.getStringValue(); },
        "id": n => { randomGetResponse_data.id = n.getNumberValue(); },
        "text": n => { randomGetResponse_data.text = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RandomGetResponse_metadata The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRandomGetResponse_metadata(randomGetResponse_metadata: Partial<RandomGetResponse_metadata> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "timestamp": n => { randomGetResponse_metadata.timestamp = n.getDateValue(); },
    }
}
export interface RandomGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * The data property
     */
    data?: RandomGetResponse_data | null;
    /**
     * The metadata property
     */
    metadata?: RandomGetResponse_metadata | null;
}
export interface RandomGetResponse_data extends AdditionalDataHolder, Parsable {
    /**
     * Name of the person who said or wrote the quote
     */
    author?: string | null;
    /**
     * Unique identifier for the quote
     */
    id?: number | null;
    /**
     * The quote text
     */
    text?: string | null;
}
export interface RandomGetResponse_metadata extends AdditionalDataHolder, Parsable {
    /**
     * The timestamp property
     */
    timestamp?: Date | null;
}
/**
 * Builds and executes requests for operations under /v1/text/quotes/random
 */
export interface RandomRequestBuilder extends BaseRequestBuilder<RandomRequestBuilder> {
    /**
     * Returns a random inspirational quote with author attribution
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RandomGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RandomGetResponse | undefined>;
    /**
     * Returns a random inspirational quote with author attribution
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RandomGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRandomGetResponse(writer: SerializationWriter, randomGetResponse: Partial<RandomGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!randomGetResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<RandomGetResponse_data>("data", randomGetResponse.data, serializeRandomGetResponse_data);
    writer.writeObjectValue<RandomGetResponse_metadata>("metadata", randomGetResponse.metadata, serializeRandomGetResponse_metadata);
    writer.writeAdditionalData(randomGetResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RandomGetResponse_data The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRandomGetResponse_data(writer: SerializationWriter, randomGetResponse_data: Partial<RandomGetResponse_data> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!randomGetResponse_data || isSerializingDerivedType) { return; }
    writer.writeStringValue("author", randomGetResponse_data.author);
    writer.writeNumberValue("id", randomGetResponse_data.id);
    writer.writeStringValue("text", randomGetResponse_data.text);
    writer.writeAdditionalData(randomGetResponse_data.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RandomGetResponse_metadata The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRandomGetResponse_metadata(writer: SerializationWriter, randomGetResponse_metadata: Partial<RandomGetResponse_metadata> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!randomGetResponse_metadata || isSerializingDerivedType) { return; }
    writer.writeDateValue("timestamp", randomGetResponse_metadata.timestamp);
    writer.writeAdditionalData(randomGetResponse_metadata.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const RandomRequestBuilderUriTemplate = "{+baseurl}/v1/text/quotes/random";
/**
 * Metadata for all the requests in the request builder.
 */
export const RandomRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: RandomRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createRandomGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
