/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing InflationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class InflationApiTests : IDisposable
    {
        private InflationApi instance;

        public InflationApiTests()
        {
            instance = new InflationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InflationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' InflationApi
            //Assert.IsType<InflationApi>(instance);
        }

        /// <summary>
        /// Test V1FinanceInflationBatchPost
        /// </summary>
        [Fact]
        public void V1FinanceInflationBatchPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //V1FinanceInflationBatchPostRequest v1FinanceInflationBatchPostRequest = null;
            //var response = instance.V1FinanceInflationBatchPost(v1FinanceInflationBatchPostRequest);
            //Assert.IsType<V1FinanceInflationBatchPost200Response>(response);
        }

        /// <summary>
        /// Test V1FinanceInflationGet
        /// </summary>
        [Fact]
        public void V1FinanceInflationGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string country = null;
            //var response = instance.V1FinanceInflationGet(country);
            //Assert.IsType<V1FinanceInflationGet200Response>(response);
        }
    }
}
