// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.V1.Technology.Base
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\technology\base
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BaseRequestBuilderEscaped : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Technology.Base.BaseRequestBuilderEscaped"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BaseRequestBuilderEscaped(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/technology/base?from={from}&to={to}&value={value}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Technology.Base.BaseRequestBuilderEscaped"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BaseRequestBuilderEscaped(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/technology/base?from={from}&to={to}&value={value}", rawUrl)
        {
        }
        /// <summary>
        /// Convert an integer from one number base to another.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.V1.Technology.Base.BaseGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.V1.Technology.Base.BaseGetResponse?> GetAsBaseGetResponseAsync(Action<RequestConfiguration<global::ApiSdk.V1.Technology.Base.BaseRequestBuilderEscaped.BaseRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.V1.Technology.Base.BaseGetResponse> GetAsBaseGetResponseAsync(Action<RequestConfiguration<global::ApiSdk.V1.Technology.Base.BaseRequestBuilderEscaped.BaseRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ApiSdk.V1.Technology.Base.BaseGetResponse>(requestInfo, global::ApiSdk.V1.Technology.Base.BaseGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Convert an integer from one number base to another.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.V1.Technology.Base.BaseResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsBaseGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ApiSdk.V1.Technology.Base.BaseResponse?> GetAsync(Action<RequestConfiguration<global::ApiSdk.V1.Technology.Base.BaseRequestBuilderEscaped.BaseRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ApiSdk.V1.Technology.Base.BaseResponse> GetAsync(Action<RequestConfiguration<global::ApiSdk.V1.Technology.Base.BaseRequestBuilderEscaped.BaseRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ApiSdk.V1.Technology.Base.BaseResponse>(requestInfo, global::ApiSdk.V1.Technology.Base.BaseResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Convert an integer from one number base to another.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.V1.Technology.Base.BaseRequestBuilderEscaped.BaseRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::ApiSdk.V1.Technology.Base.BaseRequestBuilderEscaped.BaseRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.V1.Technology.Base.BaseRequestBuilderEscaped"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ApiSdk.V1.Technology.Base.BaseRequestBuilderEscaped WithUrl(string rawUrl)
        {
            return new global::ApiSdk.V1.Technology.Base.BaseRequestBuilderEscaped(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Convert an integer from one number base to another.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BaseRequestBuilderGetQueryParameters 
        {
            /// <summary>Source base (2, 8, 10, or 16)</summary>
            [QueryParameter("from")]
            public int? From { get; set; }
            /// <summary>Target base (2, 8, 10, or 16)</summary>
            [QueryParameter("to")]
            public int? To { get; set; }
            /// <summary>The number as a string. Accepts optional prefixes: 0x (hex), 0b (binary), 0o (octal).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("value")]
            public string? Value { get; set; }
#nullable restore
#else
            [QueryParameter("value")]
            public string Value { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class BaseRequestBuilderGetRequestConfiguration : RequestConfiguration<global::ApiSdk.V1.Technology.Base.BaseRequestBuilderEscaped.BaseRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
