/*
Requiems API

Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1EntertainmentFactsGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1EntertainmentFactsGet200ResponseData{}

// V1EntertainmentFactsGet200ResponseData struct for V1EntertainmentFactsGet200ResponseData
type V1EntertainmentFactsGet200ResponseData struct {
	// The fact text
	Fact *string `json:"fact,omitempty"`
	// The category the fact belongs to
	Category *string `json:"category,omitempty"`
	// The source or publication the fact is attributed to
	Source *string `json:"source,omitempty"`
}

// NewV1EntertainmentFactsGet200ResponseData instantiates a new V1EntertainmentFactsGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1EntertainmentFactsGet200ResponseData() *V1EntertainmentFactsGet200ResponseData {
	this := V1EntertainmentFactsGet200ResponseData{}
	return &this
}

// NewV1EntertainmentFactsGet200ResponseDataWithDefaults instantiates a new V1EntertainmentFactsGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1EntertainmentFactsGet200ResponseDataWithDefaults() *V1EntertainmentFactsGet200ResponseData {
	this := V1EntertainmentFactsGet200ResponseData{}
	return &this
}

// GetFact returns the Fact field value if set, zero value otherwise.
func (o *V1EntertainmentFactsGet200ResponseData) GetFact() string {
	if o == nil || IsNil(o.Fact) {
		var ret string
		return ret
	}
	return *o.Fact
}

// GetFactOk returns a tuple with the Fact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EntertainmentFactsGet200ResponseData) GetFactOk() (*string, bool) {
	if o == nil || IsNil(o.Fact) {
		return nil, false
	}
	return o.Fact, true
}

// HasFact returns a boolean if a field has been set.
func (o *V1EntertainmentFactsGet200ResponseData) HasFact() bool {
	if o != nil && !IsNil(o.Fact) {
		return true
	}

	return false
}

// SetFact gets a reference to the given string and assigns it to the Fact field.
func (o *V1EntertainmentFactsGet200ResponseData) SetFact(v string) {
	o.Fact = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *V1EntertainmentFactsGet200ResponseData) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EntertainmentFactsGet200ResponseData) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *V1EntertainmentFactsGet200ResponseData) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *V1EntertainmentFactsGet200ResponseData) SetCategory(v string) {
	o.Category = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *V1EntertainmentFactsGet200ResponseData) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1EntertainmentFactsGet200ResponseData) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *V1EntertainmentFactsGet200ResponseData) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *V1EntertainmentFactsGet200ResponseData) SetSource(v string) {
	o.Source = &v
}

func (o V1EntertainmentFactsGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1EntertainmentFactsGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Fact) {
		toSerialize["fact"] = o.Fact
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	return toSerialize, nil
}

type NullableV1EntertainmentFactsGet200ResponseData struct {
	value *V1EntertainmentFactsGet200ResponseData
	isSet bool
}

func (v NullableV1EntertainmentFactsGet200ResponseData) Get() *V1EntertainmentFactsGet200ResponseData {
	return v.value
}

func (v *NullableV1EntertainmentFactsGet200ResponseData) Set(val *V1EntertainmentFactsGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV1EntertainmentFactsGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV1EntertainmentFactsGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1EntertainmentFactsGet200ResponseData(val *V1EntertainmentFactsGet200ResponseData) *NullableV1EntertainmentFactsGet200ResponseData {
	return &NullableV1EntertainmentFactsGet200ResponseData{value: val, isSet: true}
}

func (v NullableV1EntertainmentFactsGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1EntertainmentFactsGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


