/*
Requiems API

Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1ValidationPhoneGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ValidationPhoneGet200ResponseData{}

// V1ValidationPhoneGet200ResponseData struct for V1ValidationPhoneGet200ResponseData
type V1ValidationPhoneGet200ResponseData struct {
	// The original number as supplied in the request
	Number *string `json:"number,omitempty"`
	// Whether the number is a valid, dialable phone number
	Valid *bool `json:"valid,omitempty"`
	// ISO 3166-1 alpha-2 country code (omitted when valid is false)
	Country *string `json:"country,omitempty"`
	// Number type: mobile, landline, landline_or_mobile, toll_free, voip, premium_rate, shared_cost, personal_number, pager, uan, voicemail, or unknown (omitted when valid is false)
	Type *string `json:"type,omitempty"`
	// International format of the number, e.g. +44 7400 123456 (omitted when valid is false)
	Formatted *string `json:"formatted,omitempty"`
	// Carrier name from phone prefix metadata (omitted when carrier cannot be determined)
	CarrierName *string `json:"carrier.name,omitempty"`
	// How the carrier was determined. Always \"metadata\" when present
	CarrierSource *string `json:"carrier.source,omitempty"`
	// true when the number type is voip
	RiskIsVoip *bool `json:"risk.is_voip,omitempty"`
	// true when the number is not tied to a physical SIM or fixed line: voip, personal_number, uan, pager, or voicemail
	RiskIsVirtual *bool `json:"risk.is_virtual,omitempty"`
}

// NewV1ValidationPhoneGet200ResponseData instantiates a new V1ValidationPhoneGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ValidationPhoneGet200ResponseData() *V1ValidationPhoneGet200ResponseData {
	this := V1ValidationPhoneGet200ResponseData{}
	return &this
}

// NewV1ValidationPhoneGet200ResponseDataWithDefaults instantiates a new V1ValidationPhoneGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ValidationPhoneGet200ResponseDataWithDefaults() *V1ValidationPhoneGet200ResponseData {
	this := V1ValidationPhoneGet200ResponseData{}
	return &this
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *V1ValidationPhoneGet200ResponseData) GetNumber() string {
	if o == nil || IsNil(o.Number) {
		var ret string
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ValidationPhoneGet200ResponseData) GetNumberOk() (*string, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *V1ValidationPhoneGet200ResponseData) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given string and assigns it to the Number field.
func (o *V1ValidationPhoneGet200ResponseData) SetNumber(v string) {
	o.Number = &v
}

// GetValid returns the Valid field value if set, zero value otherwise.
func (o *V1ValidationPhoneGet200ResponseData) GetValid() bool {
	if o == nil || IsNil(o.Valid) {
		var ret bool
		return ret
	}
	return *o.Valid
}

// GetValidOk returns a tuple with the Valid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ValidationPhoneGet200ResponseData) GetValidOk() (*bool, bool) {
	if o == nil || IsNil(o.Valid) {
		return nil, false
	}
	return o.Valid, true
}

// HasValid returns a boolean if a field has been set.
func (o *V1ValidationPhoneGet200ResponseData) HasValid() bool {
	if o != nil && !IsNil(o.Valid) {
		return true
	}

	return false
}

// SetValid gets a reference to the given bool and assigns it to the Valid field.
func (o *V1ValidationPhoneGet200ResponseData) SetValid(v bool) {
	o.Valid = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *V1ValidationPhoneGet200ResponseData) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ValidationPhoneGet200ResponseData) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *V1ValidationPhoneGet200ResponseData) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *V1ValidationPhoneGet200ResponseData) SetCountry(v string) {
	o.Country = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *V1ValidationPhoneGet200ResponseData) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ValidationPhoneGet200ResponseData) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *V1ValidationPhoneGet200ResponseData) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *V1ValidationPhoneGet200ResponseData) SetType(v string) {
	o.Type = &v
}

// GetFormatted returns the Formatted field value if set, zero value otherwise.
func (o *V1ValidationPhoneGet200ResponseData) GetFormatted() string {
	if o == nil || IsNil(o.Formatted) {
		var ret string
		return ret
	}
	return *o.Formatted
}

// GetFormattedOk returns a tuple with the Formatted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ValidationPhoneGet200ResponseData) GetFormattedOk() (*string, bool) {
	if o == nil || IsNil(o.Formatted) {
		return nil, false
	}
	return o.Formatted, true
}

// HasFormatted returns a boolean if a field has been set.
func (o *V1ValidationPhoneGet200ResponseData) HasFormatted() bool {
	if o != nil && !IsNil(o.Formatted) {
		return true
	}

	return false
}

// SetFormatted gets a reference to the given string and assigns it to the Formatted field.
func (o *V1ValidationPhoneGet200ResponseData) SetFormatted(v string) {
	o.Formatted = &v
}

// GetCarrierName returns the CarrierName field value if set, zero value otherwise.
func (o *V1ValidationPhoneGet200ResponseData) GetCarrierName() string {
	if o == nil || IsNil(o.CarrierName) {
		var ret string
		return ret
	}
	return *o.CarrierName
}

// GetCarrierNameOk returns a tuple with the CarrierName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ValidationPhoneGet200ResponseData) GetCarrierNameOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierName) {
		return nil, false
	}
	return o.CarrierName, true
}

// HasCarrierName returns a boolean if a field has been set.
func (o *V1ValidationPhoneGet200ResponseData) HasCarrierName() bool {
	if o != nil && !IsNil(o.CarrierName) {
		return true
	}

	return false
}

// SetCarrierName gets a reference to the given string and assigns it to the CarrierName field.
func (o *V1ValidationPhoneGet200ResponseData) SetCarrierName(v string) {
	o.CarrierName = &v
}

// GetCarrierSource returns the CarrierSource field value if set, zero value otherwise.
func (o *V1ValidationPhoneGet200ResponseData) GetCarrierSource() string {
	if o == nil || IsNil(o.CarrierSource) {
		var ret string
		return ret
	}
	return *o.CarrierSource
}

// GetCarrierSourceOk returns a tuple with the CarrierSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ValidationPhoneGet200ResponseData) GetCarrierSourceOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierSource) {
		return nil, false
	}
	return o.CarrierSource, true
}

// HasCarrierSource returns a boolean if a field has been set.
func (o *V1ValidationPhoneGet200ResponseData) HasCarrierSource() bool {
	if o != nil && !IsNil(o.CarrierSource) {
		return true
	}

	return false
}

// SetCarrierSource gets a reference to the given string and assigns it to the CarrierSource field.
func (o *V1ValidationPhoneGet200ResponseData) SetCarrierSource(v string) {
	o.CarrierSource = &v
}

// GetRiskIsVoip returns the RiskIsVoip field value if set, zero value otherwise.
func (o *V1ValidationPhoneGet200ResponseData) GetRiskIsVoip() bool {
	if o == nil || IsNil(o.RiskIsVoip) {
		var ret bool
		return ret
	}
	return *o.RiskIsVoip
}

// GetRiskIsVoipOk returns a tuple with the RiskIsVoip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ValidationPhoneGet200ResponseData) GetRiskIsVoipOk() (*bool, bool) {
	if o == nil || IsNil(o.RiskIsVoip) {
		return nil, false
	}
	return o.RiskIsVoip, true
}

// HasRiskIsVoip returns a boolean if a field has been set.
func (o *V1ValidationPhoneGet200ResponseData) HasRiskIsVoip() bool {
	if o != nil && !IsNil(o.RiskIsVoip) {
		return true
	}

	return false
}

// SetRiskIsVoip gets a reference to the given bool and assigns it to the RiskIsVoip field.
func (o *V1ValidationPhoneGet200ResponseData) SetRiskIsVoip(v bool) {
	o.RiskIsVoip = &v
}

// GetRiskIsVirtual returns the RiskIsVirtual field value if set, zero value otherwise.
func (o *V1ValidationPhoneGet200ResponseData) GetRiskIsVirtual() bool {
	if o == nil || IsNil(o.RiskIsVirtual) {
		var ret bool
		return ret
	}
	return *o.RiskIsVirtual
}

// GetRiskIsVirtualOk returns a tuple with the RiskIsVirtual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1ValidationPhoneGet200ResponseData) GetRiskIsVirtualOk() (*bool, bool) {
	if o == nil || IsNil(o.RiskIsVirtual) {
		return nil, false
	}
	return o.RiskIsVirtual, true
}

// HasRiskIsVirtual returns a boolean if a field has been set.
func (o *V1ValidationPhoneGet200ResponseData) HasRiskIsVirtual() bool {
	if o != nil && !IsNil(o.RiskIsVirtual) {
		return true
	}

	return false
}

// SetRiskIsVirtual gets a reference to the given bool and assigns it to the RiskIsVirtual field.
func (o *V1ValidationPhoneGet200ResponseData) SetRiskIsVirtual(v bool) {
	o.RiskIsVirtual = &v
}

func (o V1ValidationPhoneGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ValidationPhoneGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	if !IsNil(o.Valid) {
		toSerialize["valid"] = o.Valid
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Formatted) {
		toSerialize["formatted"] = o.Formatted
	}
	if !IsNil(o.CarrierName) {
		toSerialize["carrier.name"] = o.CarrierName
	}
	if !IsNil(o.CarrierSource) {
		toSerialize["carrier.source"] = o.CarrierSource
	}
	if !IsNil(o.RiskIsVoip) {
		toSerialize["risk.is_voip"] = o.RiskIsVoip
	}
	if !IsNil(o.RiskIsVirtual) {
		toSerialize["risk.is_virtual"] = o.RiskIsVirtual
	}
	return toSerialize, nil
}

type NullableV1ValidationPhoneGet200ResponseData struct {
	value *V1ValidationPhoneGet200ResponseData
	isSet bool
}

func (v NullableV1ValidationPhoneGet200ResponseData) Get() *V1ValidationPhoneGet200ResponseData {
	return v.value
}

func (v *NullableV1ValidationPhoneGet200ResponseData) Set(val *V1ValidationPhoneGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ValidationPhoneGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ValidationPhoneGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ValidationPhoneGet200ResponseData(val *V1ValidationPhoneGet200ResponseData) *NullableV1ValidationPhoneGet200ResponseData {
	return &NullableV1ValidationPhoneGet200ResponseData{value: val, isSet: true}
}

func (v NullableV1ValidationPhoneGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ValidationPhoneGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


