/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithCityGetResponse_data}
 */
// @ts-ignore
export function createWithCityGetResponse_dataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithCityGetResponse_data;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithCityGetResponse_metadata}
 */
// @ts-ignore
export function createWithCityGetResponse_metadataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithCityGetResponse_metadata;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithCityGetResponse}
 */
// @ts-ignore
export function createWithCityGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithCityGetResponse;
}
/**
 * The deserialization information for the current model
 * @param WithCityGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithCityGetResponse(withCityGetResponse: Partial<WithCityGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { withCityGetResponse.data = n.getObjectValue<WithCityGetResponse_data>(createWithCityGetResponse_dataFromDiscriminatorValue); },
        "metadata": n => { withCityGetResponse.metadata = n.getObjectValue<WithCityGetResponse_metadata>(createWithCityGetResponse_metadataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param WithCityGetResponse_data The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithCityGetResponse_data(withCityGetResponse_data: Partial<WithCityGetResponse_data> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "country": n => { withCityGetResponse_data.country = n.getStringValue(); },
        "lat": n => { withCityGetResponse_data.lat = n.getNumberValue(); },
        "lon": n => { withCityGetResponse_data.lon = n.getNumberValue(); },
        "name": n => { withCityGetResponse_data.name = n.getStringValue(); },
        "population": n => { withCityGetResponse_data.population = n.getNumberValue(); },
        "timezone": n => { withCityGetResponse_data.timezone = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param WithCityGetResponse_metadata The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithCityGetResponse_metadata(withCityGetResponse_metadata: Partial<WithCityGetResponse_metadata> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "timestamp": n => { withCityGetResponse_metadata.timestamp = n.getDateValue(); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithCityGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithCityGetResponse(writer: SerializationWriter, withCityGetResponse: Partial<WithCityGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withCityGetResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<WithCityGetResponse_data>("data", withCityGetResponse.data, serializeWithCityGetResponse_data);
    writer.writeObjectValue<WithCityGetResponse_metadata>("metadata", withCityGetResponse.metadata, serializeWithCityGetResponse_metadata);
    writer.writeAdditionalData(withCityGetResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithCityGetResponse_data The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithCityGetResponse_data(writer: SerializationWriter, withCityGetResponse_data: Partial<WithCityGetResponse_data> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withCityGetResponse_data || isSerializingDerivedType) { return; }
    writer.writeStringValue("country", withCityGetResponse_data.country);
    writer.writeNumberValue("lat", withCityGetResponse_data.lat);
    writer.writeNumberValue("lon", withCityGetResponse_data.lon);
    writer.writeStringValue("name", withCityGetResponse_data.name);
    writer.writeNumberValue("population", withCityGetResponse_data.population);
    writer.writeStringValue("timezone", withCityGetResponse_data.timezone);
    writer.writeAdditionalData(withCityGetResponse_data.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithCityGetResponse_metadata The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithCityGetResponse_metadata(writer: SerializationWriter, withCityGetResponse_metadata: Partial<WithCityGetResponse_metadata> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withCityGetResponse_metadata || isSerializingDerivedType) { return; }
    writer.writeDateValue("timestamp", withCityGetResponse_metadata.timestamp);
    writer.writeAdditionalData(withCityGetResponse_metadata.additionalData);
}
export interface WithCityGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * The data property
     */
    data?: WithCityGetResponse_data | null;
    /**
     * The metadata property
     */
    metadata?: WithCityGetResponse_metadata | null;
}
export interface WithCityGetResponse_data extends AdditionalDataHolder, Parsable {
    /**
     * ISO 3166-1 alpha-2 country code (uppercase)
     */
    country?: string | null;
    /**
     * Latitude of the city centre
     */
    lat?: number | null;
    /**
     * Longitude of the city centre
     */
    lon?: number | null;
    /**
     * Official city name as listed in the GeoNames dataset
     */
    name?: string | null;
    /**
     * City population from the GeoNames dataset
     */
    population?: number | null;
    /**
     * IANA timezone identifier for the city (e.g. "America/New_York")
     */
    timezone?: string | null;
}
export interface WithCityGetResponse_metadata extends AdditionalDataHolder, Parsable {
    /**
     * The timestamp property
     */
    timestamp?: Date | null;
}
/**
 * Builds and executes requests for operations under /v1/places/cities/{city}
 */
export interface WithCityItemRequestBuilder extends BaseRequestBuilder<WithCityItemRequestBuilder> {
    /**
     * Returns metadata for a city by name. Lookup is case-insensitive.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WithCityGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WithCityGetResponse | undefined>;
    /**
     * Returns metadata for a city by name. Lookup is case-insensitive.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithCityItemRequestBuilderUriTemplate = "{+baseurl}/v1/places/cities/{city}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithCityItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithCityItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createWithCityGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
