=begin
#Requiems API

#Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SpellCheckApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SpellCheckApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SpellCheckApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SpellCheckApi' do
    it 'should create an instance of SpellCheckApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SpellCheckApi)
    end
  end

  # unit tests for v1_text_spellcheck_post
  # Check Spelling
  # Checks the input text for spelling mistakes and returns a corrected version along with per-word corrections.
  # @param v1_text_spellcheck_post_request 
  # @param [Hash] opts the optional parameters
  # @return [V1TextSpellcheckPost200Response]
  describe 'v1_text_spellcheck_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
