# coding: utf-8

"""
    Requiems API

    Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_places_postal_code_get200_response_data import V1PlacesPostalCodeGet200ResponseData

class TestV1PlacesPostalCodeGet200ResponseData(unittest.TestCase):
    """V1PlacesPostalCodeGet200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PlacesPostalCodeGet200ResponseData:
        """Test V1PlacesPostalCodeGet200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PlacesPostalCodeGet200ResponseData`
        """
        model = V1PlacesPostalCodeGet200ResponseData()
        if include_optional:
            return V1PlacesPostalCodeGet200ResponseData(
                postal_code = '',
                city = '',
                state = '',
                country = '',
                lat = 1.337,
                lon = 1.337
            )
        else:
            return V1PlacesPostalCodeGet200ResponseData(
        )
        """

    def testV1PlacesPostalCodeGet200ResponseData(self):
        """Test V1PlacesPostalCodeGet200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
