# coding: utf-8

"""
    Requiems API

    Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_health_exercises_get200_response import V1HealthExercisesGet200Response

class TestV1HealthExercisesGet200Response(unittest.TestCase):
    """V1HealthExercisesGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1HealthExercisesGet200Response:
        """Test V1HealthExercisesGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1HealthExercisesGet200Response`
        """
        model = V1HealthExercisesGet200Response()
        if include_optional:
            return V1HealthExercisesGet200Response(
                data = openapi_client.models._v1_health_exercises_get_200_response_data._v1_health_exercises_get_200_response_data(
                    items = [
                        null
                        ], 
                    items[]/id = 56, 
                    items[]/name = '', 
                    items[]/body_parts = [
                        null
                        ], 
                    items[]/equipment = [
                        null
                        ], 
                    items[]/target_muscles = [
                        null
                        ], 
                    items[]/secondary_muscles = [
                        null
                        ], 
                    items[]/instructions = [
                        null
                        ], 
                    total = 56, 
                    page = 56, 
                    per_page = 56, ),
                metadata = openapi_client.models._v1_text_advice_get_200_response_metadata._v1_text_advice_get_200_response_metadata(
                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return V1HealthExercisesGet200Response(
        )
        """

    def testV1HealthExercisesGet200Response(self):
        """Test V1HealthExercisesGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
