# coding: utf-8

"""
    Requiems API

    Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v1_technology_counter_namespace_post200_response import V1TechnologyCounterNamespacePost200Response

class TestV1TechnologyCounterNamespacePost200Response(unittest.TestCase):
    """V1TechnologyCounterNamespacePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TechnologyCounterNamespacePost200Response:
        """Test V1TechnologyCounterNamespacePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TechnologyCounterNamespacePost200Response`
        """
        model = V1TechnologyCounterNamespacePost200Response()
        if include_optional:
            return V1TechnologyCounterNamespacePost200Response(
                data = openapi_client.models._v1_technology_counter__namespace__post_200_response_data._v1_technology_counter__namespace__post_200_response_data(
                    namespace = '', 
                    value = 56, ),
                metadata = openapi_client.models._v1_text_advice_get_200_response_metadata._v1_text_advice_get_200_response_metadata(
                    timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return V1TechnologyCounterNamespacePost200Response(
        )
        """

    def testV1TechnologyCounterNamespacePost200Response(self):
        """Test V1TechnologyCounterNamespacePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
