// <auto-generated>
/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System.Linq;
using System.Collections.Generic;

namespace Org.OpenAPITools.Client
{
    /// <summary>
    /// A class containing a CookieContainer
    /// </summary>
    public sealed class CookieContainer
    {
        /// <summary>
        /// The collection of tokens
        /// </summary>
        public System.Net.CookieContainer Value { get; } = new System.Net.CookieContainer();
    }
}
