// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ApiSdk.V1.Validation.Phone
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PhoneGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Carrier name from phone prefix metadata (omitted when carrier cannot be determined)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CarrierName { get; set; }
#nullable restore
#else
        public string CarrierName { get; set; }
#endif
        /// <summary>How the carrier was determined. Always &quot;metadata&quot; when present</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CarrierSource { get; set; }
#nullable restore
#else
        public string CarrierSource { get; set; }
#endif
        /// <summary>ISO 3166-1 alpha-2 country code (omitted when valid is false)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>International format of the number, e.g. +44 7400 123456 (omitted when valid is false)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Formatted { get; set; }
#nullable restore
#else
        public string Formatted { get; set; }
#endif
        /// <summary>The original number as supplied in the request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>true when the number is not tied to a physical SIM or fixed line: voip, personal_number, uan, pager, or voicemail</summary>
        public bool? RiskIsVirtual { get; set; }
        /// <summary>true when the number type is voip</summary>
        public bool? RiskIsVoip { get; set; }
        /// <summary>Number type: mobile, landline, landline_or_mobile, toll_free, voip, premium_rate, shared_cost, personal_number, pager, uan, voicemail, or unknown (omitted when valid is false)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>Whether the number is a valid, dialable phone number</summary>
        public bool? Valid { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::ApiSdk.V1.Validation.Phone.PhoneGetResponse_data"/> and sets the default values.
        /// </summary>
        public PhoneGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ApiSdk.V1.Validation.Phone.PhoneGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ApiSdk.V1.Validation.Phone.PhoneGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ApiSdk.V1.Validation.Phone.PhoneGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "carrier.name", n => { CarrierName = n.GetStringValue(); } },
                { "carrier.source", n => { CarrierSource = n.GetStringValue(); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "formatted", n => { Formatted = n.GetStringValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "risk.is_virtual", n => { RiskIsVirtual = n.GetBoolValue(); } },
                { "risk.is_voip", n => { RiskIsVoip = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "valid", n => { Valid = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("carrier.name", CarrierName);
            writer.WriteStringValue("carrier.source", CarrierSource);
            writer.WriteStringValue("country", Country);
            writer.WriteStringValue("formatted", Formatted);
            writer.WriteStringValue("number", Number);
            writer.WriteBoolValue("risk.is_virtual", RiskIsVirtual);
            writer.WriteBoolValue("risk.is_voip", RiskIsVoip);
            writer.WriteStringValue("type", Type);
            writer.WriteBoolValue("valid", Valid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
