// <auto-generated>
/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;
using System.Diagnostics.CodeAnalysis;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IDisposableEmailApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        DisposableEmailApiEvents Events { get; }

        /// <summary>
        /// Check Batch Emails
        /// </summary>
        /// <remarks>
        /// Validate multiple email addresses in a single request (max 100 emails)
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1NetworkingDisposableBatchPostRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableBatchPostApiResponse"/>&gt;</returns>
        Task<IV1NetworkingDisposableBatchPostApiResponse> V1NetworkingDisposableBatchPostAsync(V1NetworkingDisposableBatchPostRequest v1NetworkingDisposableBatchPostRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Check Batch Emails
        /// </summary>
        /// <remarks>
        /// Validate multiple email addresses in a single request (max 100 emails)
        /// </remarks>
        /// <param name="v1NetworkingDisposableBatchPostRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableBatchPostApiResponse"/>?&gt;</returns>
        Task<IV1NetworkingDisposableBatchPostApiResponse?> V1NetworkingDisposableBatchPostOrDefaultAsync(V1NetworkingDisposableBatchPostRequest v1NetworkingDisposableBatchPostRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Check Single Email
        /// </summary>
        /// <remarks>
        /// Validate whether an email address uses a disposable domain
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1NetworkingDisposableCheckPostRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableCheckPostApiResponse"/>&gt;</returns>
        Task<IV1NetworkingDisposableCheckPostApiResponse> V1NetworkingDisposableCheckPostAsync(V1NetworkingDisposableCheckPostRequest v1NetworkingDisposableCheckPostRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Check Single Email
        /// </summary>
        /// <remarks>
        /// Validate whether an email address uses a disposable domain
        /// </remarks>
        /// <param name="v1NetworkingDisposableCheckPostRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableCheckPostApiResponse"/>?&gt;</returns>
        Task<IV1NetworkingDisposableCheckPostApiResponse?> V1NetworkingDisposableCheckPostOrDefaultAsync(V1NetworkingDisposableCheckPostRequest v1NetworkingDisposableCheckPostRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Check Domain
        /// </summary>
        /// <remarks>
        /// Check if a specific domain is in the disposable blocklist
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="domain">The domain to check</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableDomainDomainGetApiResponse"/>&gt;</returns>
        Task<IV1NetworkingDisposableDomainDomainGetApiResponse> V1NetworkingDisposableDomainDomainGetAsync(string domain, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Check Domain
        /// </summary>
        /// <remarks>
        /// Check if a specific domain is in the disposable blocklist
        /// </remarks>
        /// <param name="domain">The domain to check</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableDomainDomainGetApiResponse"/>?&gt;</returns>
        Task<IV1NetworkingDisposableDomainDomainGetApiResponse?> V1NetworkingDisposableDomainDomainGetOrDefaultAsync(string domain, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List Domains (Paginated)
        /// </summary>
        /// <remarks>
        /// Get a paginated list of all disposable domains in the blocklist
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (default: 1) (optional)</param>
        /// <param name="perPage">Items per page (default: 100, max: 1000) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableDomainsGetApiResponse"/>&gt;</returns>
        Task<IV1NetworkingDisposableDomainsGetApiResponse> V1NetworkingDisposableDomainsGetAsync(Option<int> page = default, Option<int> perPage = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List Domains (Paginated)
        /// </summary>
        /// <remarks>
        /// Get a paginated list of all disposable domains in the blocklist
        /// </remarks>
        /// <param name="page">Page number (default: 1) (optional)</param>
        /// <param name="perPage">Items per page (default: 100, max: 1000) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableDomainsGetApiResponse"/>?&gt;</returns>
        Task<IV1NetworkingDisposableDomainsGetApiResponse?> V1NetworkingDisposableDomainsGetOrDefaultAsync(Option<int> page = default, Option<int> perPage = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Statistics
        /// </summary>
        /// <remarks>
        /// Get statistics about the disposable email blocklist
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableStatsGetApiResponse"/>&gt;</returns>
        Task<IV1NetworkingDisposableStatsGetApiResponse> V1NetworkingDisposableStatsGetAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Statistics
        /// </summary>
        /// <remarks>
        /// Get statistics about the disposable email blocklist
        /// </remarks>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableStatsGetApiResponse"/>?&gt;</returns>
        Task<IV1NetworkingDisposableStatsGetApiResponse?> V1NetworkingDisposableStatsGetOrDefaultAsync(System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IV1NetworkingDisposableBatchPostApiResponse"/>
    /// </summary>
    public interface IV1NetworkingDisposableBatchPostApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.V1NetworkingDisposableBatchPost200Response?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }
    }

    /// <summary>
    /// The <see cref="IV1NetworkingDisposableCheckPostApiResponse"/>
    /// </summary>
    public interface IV1NetworkingDisposableCheckPostApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.V1NetworkingDisposableCheckPost200Response?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }
    }

    /// <summary>
    /// The <see cref="IV1NetworkingDisposableDomainDomainGetApiResponse"/>
    /// </summary>
    public interface IV1NetworkingDisposableDomainDomainGetApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.V1NetworkingDisposableDomainDomainGet200Response?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }
    }

    /// <summary>
    /// The <see cref="IV1NetworkingDisposableDomainsGetApiResponse"/>
    /// </summary>
    public interface IV1NetworkingDisposableDomainsGetApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.V1NetworkingDisposableDomainsGet200Response?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// The <see cref="IV1NetworkingDisposableStatsGetApiResponse"/>
    /// </summary>
    public interface IV1NetworkingDisposableStatsGetApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.V1NetworkingDisposableStatsGet200Response?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class DisposableEmailApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnV1NetworkingDisposableBatchPost;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorV1NetworkingDisposableBatchPost;

        internal void ExecuteOnV1NetworkingDisposableBatchPost(DisposableEmailApi.V1NetworkingDisposableBatchPostApiResponse apiResponse)
        {
            OnV1NetworkingDisposableBatchPost?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorV1NetworkingDisposableBatchPost(Exception exception)
        {
            OnErrorV1NetworkingDisposableBatchPost?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnV1NetworkingDisposableCheckPost;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorV1NetworkingDisposableCheckPost;

        internal void ExecuteOnV1NetworkingDisposableCheckPost(DisposableEmailApi.V1NetworkingDisposableCheckPostApiResponse apiResponse)
        {
            OnV1NetworkingDisposableCheckPost?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorV1NetworkingDisposableCheckPost(Exception exception)
        {
            OnErrorV1NetworkingDisposableCheckPost?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnV1NetworkingDisposableDomainDomainGet;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorV1NetworkingDisposableDomainDomainGet;

        internal void ExecuteOnV1NetworkingDisposableDomainDomainGet(DisposableEmailApi.V1NetworkingDisposableDomainDomainGetApiResponse apiResponse)
        {
            OnV1NetworkingDisposableDomainDomainGet?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorV1NetworkingDisposableDomainDomainGet(Exception exception)
        {
            OnErrorV1NetworkingDisposableDomainDomainGet?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnV1NetworkingDisposableDomainsGet;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorV1NetworkingDisposableDomainsGet;

        internal void ExecuteOnV1NetworkingDisposableDomainsGet(DisposableEmailApi.V1NetworkingDisposableDomainsGetApiResponse apiResponse)
        {
            OnV1NetworkingDisposableDomainsGet?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorV1NetworkingDisposableDomainsGet(Exception exception)
        {
            OnErrorV1NetworkingDisposableDomainsGet?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnV1NetworkingDisposableStatsGet;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorV1NetworkingDisposableStatsGet;

        internal void ExecuteOnV1NetworkingDisposableStatsGet(DisposableEmailApi.V1NetworkingDisposableStatsGetApiResponse apiResponse)
        {
            OnV1NetworkingDisposableStatsGet?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorV1NetworkingDisposableStatsGet(Exception exception)
        {
            OnErrorV1NetworkingDisposableStatsGet?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class DisposableEmailApi : IDisposableEmailApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<DisposableEmailApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public DisposableEmailApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="ApiKeyProvider"/>
        /// </summary>
        public TokenProvider<ApiKeyToken> ApiKeyProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="DisposableEmailApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DisposableEmailApi(ILogger<DisposableEmailApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, DisposableEmailApiEvents disposableEmailApiEvents,
            TokenProvider<ApiKeyToken> apiKeyProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<DisposableEmailApi>();
            HttpClient = httpClient;
            Events = disposableEmailApiEvents;
            ApiKeyProvider = apiKeyProvider;
        }

        partial void FormatV1NetworkingDisposableBatchPost(V1NetworkingDisposableBatchPostRequest v1NetworkingDisposableBatchPostRequest);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="v1NetworkingDisposableBatchPostRequest"></param>
        /// <returns></returns>
        private void ValidateV1NetworkingDisposableBatchPost(V1NetworkingDisposableBatchPostRequest v1NetworkingDisposableBatchPostRequest)
        {
            if (v1NetworkingDisposableBatchPostRequest == null)
                throw new ArgumentNullException(nameof(v1NetworkingDisposableBatchPostRequest));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="v1NetworkingDisposableBatchPostRequest"></param>
        private void AfterV1NetworkingDisposableBatchPostDefaultImplementation(IV1NetworkingDisposableBatchPostApiResponse apiResponseLocalVar, V1NetworkingDisposableBatchPostRequest v1NetworkingDisposableBatchPostRequest)
        {
            bool suppressDefaultLog = false;
            AfterV1NetworkingDisposableBatchPost(ref suppressDefaultLog, apiResponseLocalVar, v1NetworkingDisposableBatchPostRequest);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="v1NetworkingDisposableBatchPostRequest"></param>
        partial void AfterV1NetworkingDisposableBatchPost(ref bool suppressDefaultLog, IV1NetworkingDisposableBatchPostApiResponse apiResponseLocalVar, V1NetworkingDisposableBatchPostRequest v1NetworkingDisposableBatchPostRequest);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="v1NetworkingDisposableBatchPostRequest"></param>
        private void OnErrorV1NetworkingDisposableBatchPostDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, V1NetworkingDisposableBatchPostRequest v1NetworkingDisposableBatchPostRequest)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorV1NetworkingDisposableBatchPost(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, v1NetworkingDisposableBatchPostRequest);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="v1NetworkingDisposableBatchPostRequest"></param>
        partial void OnErrorV1NetworkingDisposableBatchPost(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, V1NetworkingDisposableBatchPostRequest v1NetworkingDisposableBatchPostRequest);

        /// <summary>
        /// Check Batch Emails Validate multiple email addresses in a single request (max 100 emails)
        /// </summary>
        /// <param name="v1NetworkingDisposableBatchPostRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableBatchPostApiResponse"/>&gt;</returns>
        public async Task<IV1NetworkingDisposableBatchPostApiResponse?> V1NetworkingDisposableBatchPostOrDefaultAsync(V1NetworkingDisposableBatchPostRequest v1NetworkingDisposableBatchPostRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await V1NetworkingDisposableBatchPostAsync(v1NetworkingDisposableBatchPostRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Check Batch Emails Validate multiple email addresses in a single request (max 100 emails)
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1NetworkingDisposableBatchPostRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableBatchPostApiResponse"/>&gt;</returns>
        public async Task<IV1NetworkingDisposableBatchPostApiResponse> V1NetworkingDisposableBatchPostAsync(V1NetworkingDisposableBatchPostRequest v1NetworkingDisposableBatchPostRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateV1NetworkingDisposableBatchPost(v1NetworkingDisposableBatchPostRequest);

                FormatV1NetworkingDisposableBatchPost(v1NetworkingDisposableBatchPostRequest);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v1/networking/disposable/batch"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/v1/networking/disposable/batch");

                    httpRequestMessageLocalVar.Content = (v1NetworkingDisposableBatchPostRequest as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(v1NetworkingDisposableBatchPostRequest, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("requiems-api-key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<V1NetworkingDisposableBatchPostApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<V1NetworkingDisposableBatchPostApiResponse>();
                        V1NetworkingDisposableBatchPostApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v1/networking/disposable/batch", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterV1NetworkingDisposableBatchPostDefaultImplementation(apiResponseLocalVar, v1NetworkingDisposableBatchPostRequest);

                        Events.ExecuteOnV1NetworkingDisposableBatchPost(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorV1NetworkingDisposableBatchPostDefaultImplementation(e, "/v1/networking/disposable/batch", uriBuilderLocalVar.Path, v1NetworkingDisposableBatchPostRequest);
                Events.ExecuteOnErrorV1NetworkingDisposableBatchPost(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="V1NetworkingDisposableBatchPostApiResponse"/>
        /// </summary>
        public partial class V1NetworkingDisposableBatchPostApiResponse : Org.OpenAPITools.Client.ApiResponse, IV1NetworkingDisposableBatchPostApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<V1NetworkingDisposableBatchPostApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="V1NetworkingDisposableBatchPostApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1NetworkingDisposableBatchPostApiResponse(ILogger<V1NetworkingDisposableBatchPostApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="V1NetworkingDisposableBatchPostApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1NetworkingDisposableBatchPostApiResponse(ILogger<V1NetworkingDisposableBatchPostApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.V1NetworkingDisposableBatchPost200Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.V1NetworkingDisposableBatchPost200Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.V1NetworkingDisposableBatchPost200Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatV1NetworkingDisposableCheckPost(V1NetworkingDisposableCheckPostRequest v1NetworkingDisposableCheckPostRequest);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="v1NetworkingDisposableCheckPostRequest"></param>
        /// <returns></returns>
        private void ValidateV1NetworkingDisposableCheckPost(V1NetworkingDisposableCheckPostRequest v1NetworkingDisposableCheckPostRequest)
        {
            if (v1NetworkingDisposableCheckPostRequest == null)
                throw new ArgumentNullException(nameof(v1NetworkingDisposableCheckPostRequest));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="v1NetworkingDisposableCheckPostRequest"></param>
        private void AfterV1NetworkingDisposableCheckPostDefaultImplementation(IV1NetworkingDisposableCheckPostApiResponse apiResponseLocalVar, V1NetworkingDisposableCheckPostRequest v1NetworkingDisposableCheckPostRequest)
        {
            bool suppressDefaultLog = false;
            AfterV1NetworkingDisposableCheckPost(ref suppressDefaultLog, apiResponseLocalVar, v1NetworkingDisposableCheckPostRequest);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="v1NetworkingDisposableCheckPostRequest"></param>
        partial void AfterV1NetworkingDisposableCheckPost(ref bool suppressDefaultLog, IV1NetworkingDisposableCheckPostApiResponse apiResponseLocalVar, V1NetworkingDisposableCheckPostRequest v1NetworkingDisposableCheckPostRequest);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="v1NetworkingDisposableCheckPostRequest"></param>
        private void OnErrorV1NetworkingDisposableCheckPostDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, V1NetworkingDisposableCheckPostRequest v1NetworkingDisposableCheckPostRequest)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorV1NetworkingDisposableCheckPost(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, v1NetworkingDisposableCheckPostRequest);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="v1NetworkingDisposableCheckPostRequest"></param>
        partial void OnErrorV1NetworkingDisposableCheckPost(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, V1NetworkingDisposableCheckPostRequest v1NetworkingDisposableCheckPostRequest);

        /// <summary>
        /// Check Single Email Validate whether an email address uses a disposable domain
        /// </summary>
        /// <param name="v1NetworkingDisposableCheckPostRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableCheckPostApiResponse"/>&gt;</returns>
        public async Task<IV1NetworkingDisposableCheckPostApiResponse?> V1NetworkingDisposableCheckPostOrDefaultAsync(V1NetworkingDisposableCheckPostRequest v1NetworkingDisposableCheckPostRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await V1NetworkingDisposableCheckPostAsync(v1NetworkingDisposableCheckPostRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Check Single Email Validate whether an email address uses a disposable domain
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1NetworkingDisposableCheckPostRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableCheckPostApiResponse"/>&gt;</returns>
        public async Task<IV1NetworkingDisposableCheckPostApiResponse> V1NetworkingDisposableCheckPostAsync(V1NetworkingDisposableCheckPostRequest v1NetworkingDisposableCheckPostRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateV1NetworkingDisposableCheckPost(v1NetworkingDisposableCheckPostRequest);

                FormatV1NetworkingDisposableCheckPost(v1NetworkingDisposableCheckPostRequest);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v1/networking/disposable/check"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/v1/networking/disposable/check");

                    httpRequestMessageLocalVar.Content = (v1NetworkingDisposableCheckPostRequest as object) is System.IO.Stream stream
                        ? httpRequestMessageLocalVar.Content = new StreamContent(stream)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(v1NetworkingDisposableCheckPostRequest, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("requiems-api-key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<V1NetworkingDisposableCheckPostApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<V1NetworkingDisposableCheckPostApiResponse>();
                        V1NetworkingDisposableCheckPostApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v1/networking/disposable/check", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterV1NetworkingDisposableCheckPostDefaultImplementation(apiResponseLocalVar, v1NetworkingDisposableCheckPostRequest);

                        Events.ExecuteOnV1NetworkingDisposableCheckPost(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorV1NetworkingDisposableCheckPostDefaultImplementation(e, "/v1/networking/disposable/check", uriBuilderLocalVar.Path, v1NetworkingDisposableCheckPostRequest);
                Events.ExecuteOnErrorV1NetworkingDisposableCheckPost(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="V1NetworkingDisposableCheckPostApiResponse"/>
        /// </summary>
        public partial class V1NetworkingDisposableCheckPostApiResponse : Org.OpenAPITools.Client.ApiResponse, IV1NetworkingDisposableCheckPostApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<V1NetworkingDisposableCheckPostApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="V1NetworkingDisposableCheckPostApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1NetworkingDisposableCheckPostApiResponse(ILogger<V1NetworkingDisposableCheckPostApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="V1NetworkingDisposableCheckPostApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1NetworkingDisposableCheckPostApiResponse(ILogger<V1NetworkingDisposableCheckPostApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.V1NetworkingDisposableCheckPost200Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.V1NetworkingDisposableCheckPost200Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.V1NetworkingDisposableCheckPost200Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatV1NetworkingDisposableDomainDomainGet(ref string domain);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="domain"></param>
        /// <returns></returns>
        private void ValidateV1NetworkingDisposableDomainDomainGet(string domain)
        {
            if (domain == null)
                throw new ArgumentNullException(nameof(domain));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="domain"></param>
        private void AfterV1NetworkingDisposableDomainDomainGetDefaultImplementation(IV1NetworkingDisposableDomainDomainGetApiResponse apiResponseLocalVar, string domain)
        {
            bool suppressDefaultLog = false;
            AfterV1NetworkingDisposableDomainDomainGet(ref suppressDefaultLog, apiResponseLocalVar, domain);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="domain"></param>
        partial void AfterV1NetworkingDisposableDomainDomainGet(ref bool suppressDefaultLog, IV1NetworkingDisposableDomainDomainGetApiResponse apiResponseLocalVar, string domain);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="domain"></param>
        private void OnErrorV1NetworkingDisposableDomainDomainGetDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string domain)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorV1NetworkingDisposableDomainDomainGet(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, domain);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="domain"></param>
        partial void OnErrorV1NetworkingDisposableDomainDomainGet(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string domain);

        /// <summary>
        /// Check Domain Check if a specific domain is in the disposable blocklist
        /// </summary>
        /// <param name="domain">The domain to check</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableDomainDomainGetApiResponse"/>&gt;</returns>
        public async Task<IV1NetworkingDisposableDomainDomainGetApiResponse?> V1NetworkingDisposableDomainDomainGetOrDefaultAsync(string domain, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await V1NetworkingDisposableDomainDomainGetAsync(domain, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Check Domain Check if a specific domain is in the disposable blocklist
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="domain">The domain to check</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableDomainDomainGetApiResponse"/>&gt;</returns>
        public async Task<IV1NetworkingDisposableDomainDomainGetApiResponse> V1NetworkingDisposableDomainDomainGetAsync(string domain, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateV1NetworkingDisposableDomainDomainGet(domain);

                FormatV1NetworkingDisposableDomainDomainGet(ref domain);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v1/networking/disposable/domain/{domain}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/v1/networking/disposable/domain/{domain}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bdomain%7D", Uri.EscapeDataString(domain.ToString()));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("requiems-api-key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<V1NetworkingDisposableDomainDomainGetApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<V1NetworkingDisposableDomainDomainGetApiResponse>();
                        V1NetworkingDisposableDomainDomainGetApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v1/networking/disposable/domain/{domain}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterV1NetworkingDisposableDomainDomainGetDefaultImplementation(apiResponseLocalVar, domain);

                        Events.ExecuteOnV1NetworkingDisposableDomainDomainGet(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorV1NetworkingDisposableDomainDomainGetDefaultImplementation(e, "/v1/networking/disposable/domain/{domain}", uriBuilderLocalVar.Path, domain);
                Events.ExecuteOnErrorV1NetworkingDisposableDomainDomainGet(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="V1NetworkingDisposableDomainDomainGetApiResponse"/>
        /// </summary>
        public partial class V1NetworkingDisposableDomainDomainGetApiResponse : Org.OpenAPITools.Client.ApiResponse, IV1NetworkingDisposableDomainDomainGetApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<V1NetworkingDisposableDomainDomainGetApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="V1NetworkingDisposableDomainDomainGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1NetworkingDisposableDomainDomainGetApiResponse(ILogger<V1NetworkingDisposableDomainDomainGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="V1NetworkingDisposableDomainDomainGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1NetworkingDisposableDomainDomainGetApiResponse(ILogger<V1NetworkingDisposableDomainDomainGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.V1NetworkingDisposableDomainDomainGet200Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.V1NetworkingDisposableDomainDomainGet200Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.V1NetworkingDisposableDomainDomainGet200Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatV1NetworkingDisposableDomainsGet(ref Option<int> page, ref Option<int> perPage);

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="page"></param>
        /// <param name="perPage"></param>
        private void AfterV1NetworkingDisposableDomainsGetDefaultImplementation(IV1NetworkingDisposableDomainsGetApiResponse apiResponseLocalVar, Option<int> page, Option<int> perPage)
        {
            bool suppressDefaultLog = false;
            AfterV1NetworkingDisposableDomainsGet(ref suppressDefaultLog, apiResponseLocalVar, page, perPage);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="page"></param>
        /// <param name="perPage"></param>
        partial void AfterV1NetworkingDisposableDomainsGet(ref bool suppressDefaultLog, IV1NetworkingDisposableDomainsGetApiResponse apiResponseLocalVar, Option<int> page, Option<int> perPage);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="page"></param>
        /// <param name="perPage"></param>
        private void OnErrorV1NetworkingDisposableDomainsGetDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<int> page, Option<int> perPage)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorV1NetworkingDisposableDomainsGet(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, page, perPage);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="page"></param>
        /// <param name="perPage"></param>
        partial void OnErrorV1NetworkingDisposableDomainsGet(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<int> page, Option<int> perPage);

        /// <summary>
        /// List Domains (Paginated) Get a paginated list of all disposable domains in the blocklist
        /// </summary>
        /// <param name="page">Page number (default: 1) (optional)</param>
        /// <param name="perPage">Items per page (default: 100, max: 1000) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableDomainsGetApiResponse"/>&gt;</returns>
        public async Task<IV1NetworkingDisposableDomainsGetApiResponse?> V1NetworkingDisposableDomainsGetOrDefaultAsync(Option<int> page = default, Option<int> perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await V1NetworkingDisposableDomainsGetAsync(page, perPage, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// List Domains (Paginated) Get a paginated list of all disposable domains in the blocklist
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="page">Page number (default: 1) (optional)</param>
        /// <param name="perPage">Items per page (default: 100, max: 1000) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableDomainsGetApiResponse"/>&gt;</returns>
        public async Task<IV1NetworkingDisposableDomainsGetApiResponse> V1NetworkingDisposableDomainsGetAsync(Option<int> page = default, Option<int> perPage = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                FormatV1NetworkingDisposableDomainsGet(ref page, ref perPage);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v1/networking/disposable/domains"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/v1/networking/disposable/domains");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (page.IsSet)
                        parseQueryStringLocalVar["page"] = ClientUtils.ParameterToString(page.Value);

                    if (perPage.IsSet)
                        parseQueryStringLocalVar["per_page"] = ClientUtils.ParameterToString(perPage.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("requiems-api-key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<V1NetworkingDisposableDomainsGetApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<V1NetworkingDisposableDomainsGetApiResponse>();
                        V1NetworkingDisposableDomainsGetApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v1/networking/disposable/domains", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterV1NetworkingDisposableDomainsGetDefaultImplementation(apiResponseLocalVar, page, perPage);

                        Events.ExecuteOnV1NetworkingDisposableDomainsGet(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorV1NetworkingDisposableDomainsGetDefaultImplementation(e, "/v1/networking/disposable/domains", uriBuilderLocalVar.Path, page, perPage);
                Events.ExecuteOnErrorV1NetworkingDisposableDomainsGet(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="V1NetworkingDisposableDomainsGetApiResponse"/>
        /// </summary>
        public partial class V1NetworkingDisposableDomainsGetApiResponse : Org.OpenAPITools.Client.ApiResponse, IV1NetworkingDisposableDomainsGetApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<V1NetworkingDisposableDomainsGetApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="V1NetworkingDisposableDomainsGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1NetworkingDisposableDomainsGetApiResponse(ILogger<V1NetworkingDisposableDomainsGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="V1NetworkingDisposableDomainsGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1NetworkingDisposableDomainsGetApiResponse(ILogger<V1NetworkingDisposableDomainsGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.V1NetworkingDisposableDomainsGet200Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.V1NetworkingDisposableDomainsGet200Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.V1NetworkingDisposableDomainsGet200Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        private void AfterV1NetworkingDisposableStatsGetDefaultImplementation(IV1NetworkingDisposableStatsGetApiResponse apiResponseLocalVar)
        {
            bool suppressDefaultLog = false;
            AfterV1NetworkingDisposableStatsGet(ref suppressDefaultLog, apiResponseLocalVar);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        partial void AfterV1NetworkingDisposableStatsGet(ref bool suppressDefaultLog, IV1NetworkingDisposableStatsGetApiResponse apiResponseLocalVar);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        private void OnErrorV1NetworkingDisposableStatsGetDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorV1NetworkingDisposableStatsGet(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        partial void OnErrorV1NetworkingDisposableStatsGet(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar);

        /// <summary>
        /// Get Statistics Get statistics about the disposable email blocklist
        /// </summary>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableStatsGetApiResponse"/>&gt;</returns>
        public async Task<IV1NetworkingDisposableStatsGetApiResponse?> V1NetworkingDisposableStatsGetOrDefaultAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await V1NetworkingDisposableStatsGetAsync(cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get Statistics Get statistics about the disposable email blocklist
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1NetworkingDisposableStatsGetApiResponse"/>&gt;</returns>
        public async Task<IV1NetworkingDisposableStatsGetApiResponse> V1NetworkingDisposableStatsGetAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v1/networking/disposable/stats"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/v1/networking/disposable/stats");

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("requiems-api-key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<V1NetworkingDisposableStatsGetApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<V1NetworkingDisposableStatsGetApiResponse>();
                        V1NetworkingDisposableStatsGetApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v1/networking/disposable/stats", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterV1NetworkingDisposableStatsGetDefaultImplementation(apiResponseLocalVar);

                        Events.ExecuteOnV1NetworkingDisposableStatsGet(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorV1NetworkingDisposableStatsGetDefaultImplementation(e, "/v1/networking/disposable/stats", uriBuilderLocalVar.Path);
                Events.ExecuteOnErrorV1NetworkingDisposableStatsGet(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="V1NetworkingDisposableStatsGetApiResponse"/>
        /// </summary>
        public partial class V1NetworkingDisposableStatsGetApiResponse : Org.OpenAPITools.Client.ApiResponse, IV1NetworkingDisposableStatsGetApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<V1NetworkingDisposableStatsGetApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="V1NetworkingDisposableStatsGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1NetworkingDisposableStatsGetApiResponse(ILogger<V1NetworkingDisposableStatsGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="V1NetworkingDisposableStatsGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1NetworkingDisposableStatsGetApiResponse(ILogger<V1NetworkingDisposableStatsGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.V1NetworkingDisposableStatsGet200Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.V1NetworkingDisposableStatsGet200Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.V1NetworkingDisposableStatsGet200Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
