// <auto-generated>
/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;
using System.Diagnostics.CodeAnalysis;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface ISudokuApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        SudokuApiEvents Events { get; }

        /// <summary>
        /// Batch Generate Sudoku Puzzles
        /// </summary>
        /// <remarks>
        /// Generate up to 20 Sudoku puzzles in a single request. Results are returned in the same order as the input array. Each puzzle in the batch counts as one unit of API usage.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1EntertainmentSudokuBatchPostRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1EntertainmentSudokuBatchPostApiResponse"/>&gt;</returns>
        Task<IV1EntertainmentSudokuBatchPostApiResponse> V1EntertainmentSudokuBatchPostAsync(V1EntertainmentSudokuBatchPostRequest v1EntertainmentSudokuBatchPostRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Batch Generate Sudoku Puzzles
        /// </summary>
        /// <remarks>
        /// Generate up to 20 Sudoku puzzles in a single request. Results are returned in the same order as the input array. Each puzzle in the batch counts as one unit of API usage.
        /// </remarks>
        /// <param name="v1EntertainmentSudokuBatchPostRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1EntertainmentSudokuBatchPostApiResponse"/>?&gt;</returns>
        Task<IV1EntertainmentSudokuBatchPostApiResponse?> V1EntertainmentSudokuBatchPostOrDefaultAsync(V1EntertainmentSudokuBatchPostRequest v1EntertainmentSudokuBatchPostRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Sudoku Puzzle
        /// </summary>
        /// <remarks>
        /// Returns a randomly generated Sudoku puzzle and its solution. Difficulty defaults to medium when not specified.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="difficulty">Puzzle difficulty level. One of: easy, medium, hard. Defaults to medium. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1EntertainmentSudokuGetApiResponse"/>&gt;</returns>
        Task<IV1EntertainmentSudokuGetApiResponse> V1EntertainmentSudokuGetAsync(Option<string> difficulty = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Sudoku Puzzle
        /// </summary>
        /// <remarks>
        /// Returns a randomly generated Sudoku puzzle and its solution. Difficulty defaults to medium when not specified.
        /// </remarks>
        /// <param name="difficulty">Puzzle difficulty level. One of: easy, medium, hard. Defaults to medium. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1EntertainmentSudokuGetApiResponse"/>?&gt;</returns>
        Task<IV1EntertainmentSudokuGetApiResponse?> V1EntertainmentSudokuGetOrDefaultAsync(Option<string> difficulty = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IV1EntertainmentSudokuBatchPostApiResponse"/>
    /// </summary>
    public interface IV1EntertainmentSudokuBatchPostApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.V1EntertainmentSudokuBatchPost200Response?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 403 Forbidden
        /// </summary>
        /// <returns></returns>
        bool IsForbidden { get; }

        /// <summary>
        /// Returns true if the response is 422 UnprocessableContent
        /// </summary>
        /// <returns></returns>
        bool IsUnprocessableContent { get; }
    }

    /// <summary>
    /// The <see cref="IV1EntertainmentSudokuGetApiResponse"/>
    /// </summary>
    public interface IV1EntertainmentSudokuGetApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.V1EntertainmentSudokuGet200Response?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 403 Forbidden
        /// </summary>
        /// <returns></returns>
        bool IsForbidden { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class SudokuApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnV1EntertainmentSudokuBatchPost;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorV1EntertainmentSudokuBatchPost;

        internal void ExecuteOnV1EntertainmentSudokuBatchPost(SudokuApi.V1EntertainmentSudokuBatchPostApiResponse apiResponse)
        {
            OnV1EntertainmentSudokuBatchPost?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorV1EntertainmentSudokuBatchPost(Exception exception)
        {
            OnErrorV1EntertainmentSudokuBatchPost?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnV1EntertainmentSudokuGet;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorV1EntertainmentSudokuGet;

        internal void ExecuteOnV1EntertainmentSudokuGet(SudokuApi.V1EntertainmentSudokuGetApiResponse apiResponse)
        {
            OnV1EntertainmentSudokuGet?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorV1EntertainmentSudokuGet(Exception exception)
        {
            OnErrorV1EntertainmentSudokuGet?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class SudokuApi : ISudokuApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<SudokuApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public SudokuApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="ApiKeyProvider"/>
        /// </summary>
        public TokenProvider<ApiKeyToken> ApiKeyProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="SudokuApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SudokuApi(ILogger<SudokuApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, SudokuApiEvents sudokuApiEvents,
            TokenProvider<ApiKeyToken> apiKeyProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<SudokuApi>();
            HttpClient = httpClient;
            Events = sudokuApiEvents;
            ApiKeyProvider = apiKeyProvider;
        }

        partial void FormatV1EntertainmentSudokuBatchPost(V1EntertainmentSudokuBatchPostRequest v1EntertainmentSudokuBatchPostRequest);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="v1EntertainmentSudokuBatchPostRequest"></param>
        /// <returns></returns>
        private void ValidateV1EntertainmentSudokuBatchPost(V1EntertainmentSudokuBatchPostRequest v1EntertainmentSudokuBatchPostRequest)
        {
            if (v1EntertainmentSudokuBatchPostRequest == null)
                throw new ArgumentNullException(nameof(v1EntertainmentSudokuBatchPostRequest));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="v1EntertainmentSudokuBatchPostRequest"></param>
        private void AfterV1EntertainmentSudokuBatchPostDefaultImplementation(IV1EntertainmentSudokuBatchPostApiResponse apiResponseLocalVar, V1EntertainmentSudokuBatchPostRequest v1EntertainmentSudokuBatchPostRequest)
        {
            bool suppressDefaultLog = false;
            AfterV1EntertainmentSudokuBatchPost(ref suppressDefaultLog, apiResponseLocalVar, v1EntertainmentSudokuBatchPostRequest);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="v1EntertainmentSudokuBatchPostRequest"></param>
        partial void AfterV1EntertainmentSudokuBatchPost(ref bool suppressDefaultLog, IV1EntertainmentSudokuBatchPostApiResponse apiResponseLocalVar, V1EntertainmentSudokuBatchPostRequest v1EntertainmentSudokuBatchPostRequest);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="v1EntertainmentSudokuBatchPostRequest"></param>
        private void OnErrorV1EntertainmentSudokuBatchPostDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, V1EntertainmentSudokuBatchPostRequest v1EntertainmentSudokuBatchPostRequest)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorV1EntertainmentSudokuBatchPost(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, v1EntertainmentSudokuBatchPostRequest);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="v1EntertainmentSudokuBatchPostRequest"></param>
        partial void OnErrorV1EntertainmentSudokuBatchPost(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, V1EntertainmentSudokuBatchPostRequest v1EntertainmentSudokuBatchPostRequest);

        /// <summary>
        /// Batch Generate Sudoku Puzzles Generate up to 20 Sudoku puzzles in a single request. Results are returned in the same order as the input array. Each puzzle in the batch counts as one unit of API usage.
        /// </summary>
        /// <param name="v1EntertainmentSudokuBatchPostRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1EntertainmentSudokuBatchPostApiResponse"/>&gt;</returns>
        public async Task<IV1EntertainmentSudokuBatchPostApiResponse?> V1EntertainmentSudokuBatchPostOrDefaultAsync(V1EntertainmentSudokuBatchPostRequest v1EntertainmentSudokuBatchPostRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await V1EntertainmentSudokuBatchPostAsync(v1EntertainmentSudokuBatchPostRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Batch Generate Sudoku Puzzles Generate up to 20 Sudoku puzzles in a single request. Results are returned in the same order as the input array. Each puzzle in the batch counts as one unit of API usage.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="v1EntertainmentSudokuBatchPostRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1EntertainmentSudokuBatchPostApiResponse"/>&gt;</returns>
        public async Task<IV1EntertainmentSudokuBatchPostApiResponse> V1EntertainmentSudokuBatchPostAsync(V1EntertainmentSudokuBatchPostRequest v1EntertainmentSudokuBatchPostRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateV1EntertainmentSudokuBatchPost(v1EntertainmentSudokuBatchPostRequest);

                FormatV1EntertainmentSudokuBatchPost(v1EntertainmentSudokuBatchPostRequest);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v1/entertainment/sudoku/batch"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/v1/entertainment/sudoku/batch");

                    httpRequestMessageLocalVar.Content = (v1EntertainmentSudokuBatchPostRequest as object) is Org.OpenAPITools.Client.FileParameter fileParameterLocalVar
                        ? httpRequestMessageLocalVar.Content = new StreamContent(fileParameterLocalVar.Content)
                        : httpRequestMessageLocalVar.Content = new StringContent(JsonSerializer.Serialize(v1EntertainmentSudokuBatchPostRequest, _jsonSerializerOptions));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("requiems-api-key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] contentTypes = new string[] {
                        "application/json"
                    };

                    string? contentTypeLocalVar = ClientUtils.SelectHeaderContentType(contentTypes);

                    if (contentTypeLocalVar != null && httpRequestMessageLocalVar.Content != null)
                        httpRequestMessageLocalVar.Content.Headers.ContentType = new MediaTypeHeaderValue(contentTypeLocalVar);

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Post;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<V1EntertainmentSudokuBatchPostApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<V1EntertainmentSudokuBatchPostApiResponse>();
                        V1EntertainmentSudokuBatchPostApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v1/entertainment/sudoku/batch", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterV1EntertainmentSudokuBatchPostDefaultImplementation(apiResponseLocalVar, v1EntertainmentSudokuBatchPostRequest);

                        Events.ExecuteOnV1EntertainmentSudokuBatchPost(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorV1EntertainmentSudokuBatchPostDefaultImplementation(e, "/v1/entertainment/sudoku/batch", uriBuilderLocalVar.Path, v1EntertainmentSudokuBatchPostRequest);
                Events.ExecuteOnErrorV1EntertainmentSudokuBatchPost(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="V1EntertainmentSudokuBatchPostApiResponse"/>
        /// </summary>
        public partial class V1EntertainmentSudokuBatchPostApiResponse : Org.OpenAPITools.Client.ApiResponse, IV1EntertainmentSudokuBatchPostApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<V1EntertainmentSudokuBatchPostApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="V1EntertainmentSudokuBatchPostApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1EntertainmentSudokuBatchPostApiResponse(ILogger<V1EntertainmentSudokuBatchPostApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="V1EntertainmentSudokuBatchPostApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1EntertainmentSudokuBatchPostApiResponse(ILogger<V1EntertainmentSudokuBatchPostApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.V1EntertainmentSudokuBatchPost200Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.V1EntertainmentSudokuBatchPost200Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.V1EntertainmentSudokuBatchPost200Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public bool IsForbidden => 403 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public bool IsUnprocessableContent => 422 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatV1EntertainmentSudokuGet(ref Option<string> difficulty);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="difficulty"></param>
        /// <returns></returns>
        private void ValidateV1EntertainmentSudokuGet(Option<string> difficulty)
        {
            if (difficulty.IsSet && difficulty.Value == null)
                throw new ArgumentNullException(nameof(difficulty));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="difficulty"></param>
        private void AfterV1EntertainmentSudokuGetDefaultImplementation(IV1EntertainmentSudokuGetApiResponse apiResponseLocalVar, Option<string> difficulty)
        {
            bool suppressDefaultLog = false;
            AfterV1EntertainmentSudokuGet(ref suppressDefaultLog, apiResponseLocalVar, difficulty);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="difficulty"></param>
        partial void AfterV1EntertainmentSudokuGet(ref bool suppressDefaultLog, IV1EntertainmentSudokuGetApiResponse apiResponseLocalVar, Option<string> difficulty);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="difficulty"></param>
        private void OnErrorV1EntertainmentSudokuGetDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> difficulty)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorV1EntertainmentSudokuGet(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, difficulty);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="difficulty"></param>
        partial void OnErrorV1EntertainmentSudokuGet(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, Option<string> difficulty);

        /// <summary>
        /// Get Sudoku Puzzle Returns a randomly generated Sudoku puzzle and its solution. Difficulty defaults to medium when not specified.
        /// </summary>
        /// <param name="difficulty">Puzzle difficulty level. One of: easy, medium, hard. Defaults to medium. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1EntertainmentSudokuGetApiResponse"/>&gt;</returns>
        public async Task<IV1EntertainmentSudokuGetApiResponse?> V1EntertainmentSudokuGetOrDefaultAsync(Option<string> difficulty = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await V1EntertainmentSudokuGetAsync(difficulty, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get Sudoku Puzzle Returns a randomly generated Sudoku puzzle and its solution. Difficulty defaults to medium when not specified.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="difficulty">Puzzle difficulty level. One of: easy, medium, hard. Defaults to medium. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1EntertainmentSudokuGetApiResponse"/>&gt;</returns>
        public async Task<IV1EntertainmentSudokuGetApiResponse> V1EntertainmentSudokuGetAsync(Option<string> difficulty = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateV1EntertainmentSudokuGet(difficulty);

                FormatV1EntertainmentSudokuGet(ref difficulty);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v1/entertainment/sudoku"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/v1/entertainment/sudoku");

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    if (difficulty.IsSet)
                        parseQueryStringLocalVar["difficulty"] = ClientUtils.ParameterToString(difficulty.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("requiems-api-key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<V1EntertainmentSudokuGetApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<V1EntertainmentSudokuGetApiResponse>();
                        V1EntertainmentSudokuGetApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v1/entertainment/sudoku", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterV1EntertainmentSudokuGetDefaultImplementation(apiResponseLocalVar, difficulty);

                        Events.ExecuteOnV1EntertainmentSudokuGet(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorV1EntertainmentSudokuGetDefaultImplementation(e, "/v1/entertainment/sudoku", uriBuilderLocalVar.Path, difficulty);
                Events.ExecuteOnErrorV1EntertainmentSudokuGet(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="V1EntertainmentSudokuGetApiResponse"/>
        /// </summary>
        public partial class V1EntertainmentSudokuGetApiResponse : Org.OpenAPITools.Client.ApiResponse, IV1EntertainmentSudokuGetApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<V1EntertainmentSudokuGetApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="V1EntertainmentSudokuGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1EntertainmentSudokuGetApiResponse(ILogger<V1EntertainmentSudokuGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="V1EntertainmentSudokuGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1EntertainmentSudokuGetApiResponse(ILogger<V1EntertainmentSudokuGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.V1EntertainmentSudokuGet200Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.V1EntertainmentSudokuGet200Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.V1EntertainmentSudokuGet200Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public bool IsForbidden => 403 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
