=begin
#Requiems API

#Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::CommoditiesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CommoditiesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::CommoditiesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommoditiesApi' do
    it 'should create an instance of CommoditiesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::CommoditiesApi)
    end
  end

  # unit tests for v1_finance_commodities_commodity_get
  # Get Commodity Price
  # Returns the latest annual average price and up to 10 years of historical data for the requested commodity slug.
  # @param commodity Commodity slug (e.g. gold, silver, oil). See supported slugs below.
  # @param [Hash] opts the optional parameters
  # @return [V1FinanceCommoditiesCommodityGet200Response]
  describe 'v1_finance_commodities_commodity_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
