/*
Requiems API

Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the V1PlacesPostalCodeGet200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1PlacesPostalCodeGet200ResponseData{}

// V1PlacesPostalCodeGet200ResponseData struct for V1PlacesPostalCodeGet200ResponseData
type V1PlacesPostalCodeGet200ResponseData struct {
	// The postal code as stored in the dataset
	PostalCode *string `json:"postal_code,omitempty"`
	// Primary city or place name for the postal code
	City *string `json:"city,omitempty"`
	// State, province, or administrative region name
	State *string `json:"state,omitempty"`
	// ISO 3166-1 alpha-2 country code (uppercase)
	Country *string `json:"country,omitempty"`
	// Latitude of the postal code centroid
	Lat *float32 `json:"lat,omitempty"`
	// Longitude of the postal code centroid
	Lon *float32 `json:"lon,omitempty"`
}

// NewV1PlacesPostalCodeGet200ResponseData instantiates a new V1PlacesPostalCodeGet200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1PlacesPostalCodeGet200ResponseData() *V1PlacesPostalCodeGet200ResponseData {
	this := V1PlacesPostalCodeGet200ResponseData{}
	return &this
}

// NewV1PlacesPostalCodeGet200ResponseDataWithDefaults instantiates a new V1PlacesPostalCodeGet200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1PlacesPostalCodeGet200ResponseDataWithDefaults() *V1PlacesPostalCodeGet200ResponseData {
	this := V1PlacesPostalCodeGet200ResponseData{}
	return &this
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *V1PlacesPostalCodeGet200ResponseData) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode) {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PlacesPostalCodeGet200ResponseData) GetPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *V1PlacesPostalCodeGet200ResponseData) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *V1PlacesPostalCodeGet200ResponseData) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *V1PlacesPostalCodeGet200ResponseData) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PlacesPostalCodeGet200ResponseData) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *V1PlacesPostalCodeGet200ResponseData) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *V1PlacesPostalCodeGet200ResponseData) SetCity(v string) {
	o.City = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *V1PlacesPostalCodeGet200ResponseData) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PlacesPostalCodeGet200ResponseData) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *V1PlacesPostalCodeGet200ResponseData) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *V1PlacesPostalCodeGet200ResponseData) SetState(v string) {
	o.State = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *V1PlacesPostalCodeGet200ResponseData) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PlacesPostalCodeGet200ResponseData) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *V1PlacesPostalCodeGet200ResponseData) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *V1PlacesPostalCodeGet200ResponseData) SetCountry(v string) {
	o.Country = &v
}

// GetLat returns the Lat field value if set, zero value otherwise.
func (o *V1PlacesPostalCodeGet200ResponseData) GetLat() float32 {
	if o == nil || IsNil(o.Lat) {
		var ret float32
		return ret
	}
	return *o.Lat
}

// GetLatOk returns a tuple with the Lat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PlacesPostalCodeGet200ResponseData) GetLatOk() (*float32, bool) {
	if o == nil || IsNil(o.Lat) {
		return nil, false
	}
	return o.Lat, true
}

// HasLat returns a boolean if a field has been set.
func (o *V1PlacesPostalCodeGet200ResponseData) HasLat() bool {
	if o != nil && !IsNil(o.Lat) {
		return true
	}

	return false
}

// SetLat gets a reference to the given float32 and assigns it to the Lat field.
func (o *V1PlacesPostalCodeGet200ResponseData) SetLat(v float32) {
	o.Lat = &v
}

// GetLon returns the Lon field value if set, zero value otherwise.
func (o *V1PlacesPostalCodeGet200ResponseData) GetLon() float32 {
	if o == nil || IsNil(o.Lon) {
		var ret float32
		return ret
	}
	return *o.Lon
}

// GetLonOk returns a tuple with the Lon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PlacesPostalCodeGet200ResponseData) GetLonOk() (*float32, bool) {
	if o == nil || IsNil(o.Lon) {
		return nil, false
	}
	return o.Lon, true
}

// HasLon returns a boolean if a field has been set.
func (o *V1PlacesPostalCodeGet200ResponseData) HasLon() bool {
	if o != nil && !IsNil(o.Lon) {
		return true
	}

	return false
}

// SetLon gets a reference to the given float32 and assigns it to the Lon field.
func (o *V1PlacesPostalCodeGet200ResponseData) SetLon(v float32) {
	o.Lon = &v
}

func (o V1PlacesPostalCodeGet200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1PlacesPostalCodeGet200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PostalCode) {
		toSerialize["postal_code"] = o.PostalCode
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Lat) {
		toSerialize["lat"] = o.Lat
	}
	if !IsNil(o.Lon) {
		toSerialize["lon"] = o.Lon
	}
	return toSerialize, nil
}

type NullableV1PlacesPostalCodeGet200ResponseData struct {
	value *V1PlacesPostalCodeGet200ResponseData
	isSet bool
}

func (v NullableV1PlacesPostalCodeGet200ResponseData) Get() *V1PlacesPostalCodeGet200ResponseData {
	return v.value
}

func (v *NullableV1PlacesPostalCodeGet200ResponseData) Set(val *V1PlacesPostalCodeGet200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PlacesPostalCodeGet200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PlacesPostalCodeGet200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PlacesPostalCodeGet200ResponseData(val *V1PlacesPostalCodeGet200ResponseData) *NullableV1PlacesPostalCodeGet200ResponseData {
	return &NullableV1PlacesPostalCodeGet200ResponseData{value: val, isSet: true}
}

func (v NullableV1PlacesPostalCodeGet200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PlacesPostalCodeGet200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


