/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing V1TechnologyCounterNamespaceGet200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1TechnologyCounterNamespaceGet200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1TechnologyCounterNamespaceGet200ResponseData
        //private V1TechnologyCounterNamespaceGet200ResponseData instance;

        public V1TechnologyCounterNamespaceGet200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of V1TechnologyCounterNamespaceGet200ResponseData
            //instance = new V1TechnologyCounterNamespaceGet200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1TechnologyCounterNamespaceGet200ResponseData
        /// </summary>
        [Fact]
        public void V1TechnologyCounterNamespaceGet200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1TechnologyCounterNamespaceGet200ResponseData
            //Assert.IsType<V1TechnologyCounterNamespaceGet200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
