/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing V1TextAdviceGet200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1TextAdviceGet200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1TextAdviceGet200ResponseData
        //private V1TextAdviceGet200ResponseData instance;

        public V1TextAdviceGet200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of V1TextAdviceGet200ResponseData
            //instance = new V1TextAdviceGet200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1TextAdviceGet200ResponseData
        /// </summary>
        [Fact]
        public void V1TextAdviceGet200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1TextAdviceGet200ResponseData
            //Assert.IsType<V1TextAdviceGet200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Advice'
        /// </summary>
        [Fact]
        public void AdviceTest()
        {
            // TODO unit test for the property 'Advice'
        }
    }
}
