// <auto-generated>
/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// V1FinanceIbanIbanGet200ResponseData
    /// </summary>
    public partial class V1FinanceIbanIbanGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1FinanceIbanIbanGet200ResponseData" /> class.
        /// </summary>
        /// <param name="iban">The normalised IBAN (spaces stripped, uppercased)</param>
        /// <param name="valid">true if the IBAN passed length and ISO 13616 checksum validation</param>
        /// <param name="country">Full country name (empty if the country code is not in the registry)</param>
        /// <param name="bankCode">Bank identifier extracted from the BBAN (empty if country not in registry or positions not defined)</param>
        /// <param name="account">Account number extracted from the BBAN (empty if country not in registry or positions not defined)</param>
        [JsonConstructor]
        public V1FinanceIbanIbanGet200ResponseData(Option<string?> iban = default, Option<bool?> valid = default, Option<string?> country = default, Option<string?> bankCode = default, Option<string?> account = default)
        {
            IbanOption = iban;
            ValidOption = valid;
            CountryOption = country;
            BankCodeOption = bankCode;
            AccountOption = account;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Iban
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IbanOption { get; private set; }

        /// <summary>
        /// The normalised IBAN (spaces stripped, uppercased)
        /// </summary>
        /// <value>The normalised IBAN (spaces stripped, uppercased)</value>
        [JsonPropertyName("iban")]
        public string? Iban { get { return this.IbanOption.Value; } set { this.IbanOption = new(value); } }

        /// <summary>
        /// Used to track the state of Valid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ValidOption { get; private set; }

        /// <summary>
        /// true if the IBAN passed length and ISO 13616 checksum validation
        /// </summary>
        /// <value>true if the IBAN passed length and ISO 13616 checksum validation</value>
        [JsonPropertyName("valid")]
        public bool? Valid { get { return this.ValidOption.Value; } set { this.ValidOption = new(value); } }

        /// <summary>
        /// Used to track the state of Country
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CountryOption { get; private set; }

        /// <summary>
        /// Full country name (empty if the country code is not in the registry)
        /// </summary>
        /// <value>Full country name (empty if the country code is not in the registry)</value>
        [JsonPropertyName("country")]
        public string? Country { get { return this.CountryOption.Value; } set { this.CountryOption = new(value); } }

        /// <summary>
        /// Used to track the state of BankCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> BankCodeOption { get; private set; }

        /// <summary>
        /// Bank identifier extracted from the BBAN (empty if country not in registry or positions not defined)
        /// </summary>
        /// <value>Bank identifier extracted from the BBAN (empty if country not in registry or positions not defined)</value>
        [JsonPropertyName("bank_code")]
        public string? BankCode { get { return this.BankCodeOption.Value; } set { this.BankCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Account
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AccountOption { get; private set; }

        /// <summary>
        /// Account number extracted from the BBAN (empty if country not in registry or positions not defined)
        /// </summary>
        /// <value>Account number extracted from the BBAN (empty if country not in registry or positions not defined)</value>
        [JsonPropertyName("account")]
        public string? Account { get { return this.AccountOption.Value; } set { this.AccountOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1FinanceIbanIbanGet200ResponseData {\n");
            sb.Append("  Iban: ").Append(Iban).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  BankCode: ").Append(BankCode).Append("\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V1FinanceIbanIbanGet200ResponseData" />
    /// </summary>
    public class V1FinanceIbanIbanGet200ResponseDataJsonConverter : JsonConverter<V1FinanceIbanIbanGet200ResponseData>
    {
        /// <summary>
        /// Deserializes json to <see cref="V1FinanceIbanIbanGet200ResponseData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V1FinanceIbanIbanGet200ResponseData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> iban = default;
            Option<bool?> valid = default;
            Option<string?> country = default;
            Option<string?> bankCode = default;
            Option<string?> account = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "iban":
                            iban = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "valid":
                            valid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "country":
                            country = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "bank_code":
                            bankCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "account":
                            account = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (iban.IsSet && iban.Value == null)
                throw new ArgumentNullException(nameof(iban), "Property is not nullable for class V1FinanceIbanIbanGet200ResponseData.");

            if (valid.IsSet && valid.Value == null)
                throw new ArgumentNullException(nameof(valid), "Property is not nullable for class V1FinanceIbanIbanGet200ResponseData.");

            if (country.IsSet && country.Value == null)
                throw new ArgumentNullException(nameof(country), "Property is not nullable for class V1FinanceIbanIbanGet200ResponseData.");

            if (bankCode.IsSet && bankCode.Value == null)
                throw new ArgumentNullException(nameof(bankCode), "Property is not nullable for class V1FinanceIbanIbanGet200ResponseData.");

            if (account.IsSet && account.Value == null)
                throw new ArgumentNullException(nameof(account), "Property is not nullable for class V1FinanceIbanIbanGet200ResponseData.");

            return new V1FinanceIbanIbanGet200ResponseData(iban, valid, country, bankCode, account);
        }

        /// <summary>
        /// Serializes a <see cref="V1FinanceIbanIbanGet200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v1FinanceIbanIbanGet200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V1FinanceIbanIbanGet200ResponseData v1FinanceIbanIbanGet200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v1FinanceIbanIbanGet200ResponseData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V1FinanceIbanIbanGet200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v1FinanceIbanIbanGet200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V1FinanceIbanIbanGet200ResponseData v1FinanceIbanIbanGet200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v1FinanceIbanIbanGet200ResponseData.IbanOption.IsSet && v1FinanceIbanIbanGet200ResponseData.Iban == null)
                throw new ArgumentNullException(nameof(v1FinanceIbanIbanGet200ResponseData.Iban), "Property is required for class V1FinanceIbanIbanGet200ResponseData.");

            if (v1FinanceIbanIbanGet200ResponseData.CountryOption.IsSet && v1FinanceIbanIbanGet200ResponseData.Country == null)
                throw new ArgumentNullException(nameof(v1FinanceIbanIbanGet200ResponseData.Country), "Property is required for class V1FinanceIbanIbanGet200ResponseData.");

            if (v1FinanceIbanIbanGet200ResponseData.BankCodeOption.IsSet && v1FinanceIbanIbanGet200ResponseData.BankCode == null)
                throw new ArgumentNullException(nameof(v1FinanceIbanIbanGet200ResponseData.BankCode), "Property is required for class V1FinanceIbanIbanGet200ResponseData.");

            if (v1FinanceIbanIbanGet200ResponseData.AccountOption.IsSet && v1FinanceIbanIbanGet200ResponseData.Account == null)
                throw new ArgumentNullException(nameof(v1FinanceIbanIbanGet200ResponseData.Account), "Property is required for class V1FinanceIbanIbanGet200ResponseData.");

            if (v1FinanceIbanIbanGet200ResponseData.IbanOption.IsSet)
                writer.WriteString("iban", v1FinanceIbanIbanGet200ResponseData.Iban);

            if (v1FinanceIbanIbanGet200ResponseData.ValidOption.IsSet)
                writer.WriteBoolean("valid", v1FinanceIbanIbanGet200ResponseData.ValidOption.Value!.Value);

            if (v1FinanceIbanIbanGet200ResponseData.CountryOption.IsSet)
                writer.WriteString("country", v1FinanceIbanIbanGet200ResponseData.Country);

            if (v1FinanceIbanIbanGet200ResponseData.BankCodeOption.IsSet)
                writer.WriteString("bank_code", v1FinanceIbanIbanGet200ResponseData.BankCode);

            if (v1FinanceIbanIbanGet200ResponseData.AccountOption.IsSet)
                writer.WriteString("account", v1FinanceIbanIbanGet200ResponseData.Account);
        }
    }
}
