// <auto-generated>
/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// V1TechnologyBaseGet200ResponseData
    /// </summary>
    public partial class V1TechnologyBaseGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1TechnologyBaseGet200ResponseData" /> class.
        /// </summary>
        /// <param name="input">The original value as provided in the request</param>
        /// <param name="from">The source base</param>
        /// <param name="to">The target base</param>
        /// <param name="result">The converted value in the target base</param>
        [JsonConstructor]
        public V1TechnologyBaseGet200ResponseData(Option<string?> input = default, Option<int?> from = default, Option<int?> to = default, Option<string?> result = default)
        {
            InputOption = input;
            FromOption = from;
            ToOption = to;
            ResultOption = result;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Input
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> InputOption { get; private set; }

        /// <summary>
        /// The original value as provided in the request
        /// </summary>
        /// <value>The original value as provided in the request</value>
        [JsonPropertyName("input")]
        public string? Input { get { return this.InputOption.Value; } set { this.InputOption = new(value); } }

        /// <summary>
        /// Used to track the state of From
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FromOption { get; private set; }

        /// <summary>
        /// The source base
        /// </summary>
        /// <value>The source base</value>
        [JsonPropertyName("from")]
        public int? From { get { return this.FromOption.Value; } set { this.FromOption = new(value); } }

        /// <summary>
        /// Used to track the state of To
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ToOption { get; private set; }

        /// <summary>
        /// The target base
        /// </summary>
        /// <value>The target base</value>
        [JsonPropertyName("to")]
        public int? To { get { return this.ToOption.Value; } set { this.ToOption = new(value); } }

        /// <summary>
        /// Used to track the state of Result
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ResultOption { get; private set; }

        /// <summary>
        /// The converted value in the target base
        /// </summary>
        /// <value>The converted value in the target base</value>
        [JsonPropertyName("result")]
        public string? Result { get { return this.ResultOption.Value; } set { this.ResultOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1TechnologyBaseGet200ResponseData {\n");
            sb.Append("  Input: ").Append(Input).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="V1TechnologyBaseGet200ResponseData" />
    /// </summary>
    public class V1TechnologyBaseGet200ResponseDataJsonConverter : JsonConverter<V1TechnologyBaseGet200ResponseData>
    {
        /// <summary>
        /// Deserializes json to <see cref="V1TechnologyBaseGet200ResponseData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override V1TechnologyBaseGet200ResponseData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> input = default;
            Option<int?> from = default;
            Option<int?> to = default;
            Option<string?> result = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "input":
                            input = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "from":
                            from = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "to":
                            to = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "result":
                            result = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (input.IsSet && input.Value == null)
                throw new ArgumentNullException(nameof(input), "Property is not nullable for class V1TechnologyBaseGet200ResponseData.");

            if (from.IsSet && from.Value == null)
                throw new ArgumentNullException(nameof(from), "Property is not nullable for class V1TechnologyBaseGet200ResponseData.");

            if (to.IsSet && to.Value == null)
                throw new ArgumentNullException(nameof(to), "Property is not nullable for class V1TechnologyBaseGet200ResponseData.");

            if (result.IsSet && result.Value == null)
                throw new ArgumentNullException(nameof(result), "Property is not nullable for class V1TechnologyBaseGet200ResponseData.");

            return new V1TechnologyBaseGet200ResponseData(input, from, to, result);
        }

        /// <summary>
        /// Serializes a <see cref="V1TechnologyBaseGet200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v1TechnologyBaseGet200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, V1TechnologyBaseGet200ResponseData v1TechnologyBaseGet200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, v1TechnologyBaseGet200ResponseData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="V1TechnologyBaseGet200ResponseData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="v1TechnologyBaseGet200ResponseData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, V1TechnologyBaseGet200ResponseData v1TechnologyBaseGet200ResponseData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (v1TechnologyBaseGet200ResponseData.InputOption.IsSet && v1TechnologyBaseGet200ResponseData.Input == null)
                throw new ArgumentNullException(nameof(v1TechnologyBaseGet200ResponseData.Input), "Property is required for class V1TechnologyBaseGet200ResponseData.");

            if (v1TechnologyBaseGet200ResponseData.ResultOption.IsSet && v1TechnologyBaseGet200ResponseData.Result == null)
                throw new ArgumentNullException(nameof(v1TechnologyBaseGet200ResponseData.Result), "Property is required for class V1TechnologyBaseGet200ResponseData.");

            if (v1TechnologyBaseGet200ResponseData.InputOption.IsSet)
                writer.WriteString("input", v1TechnologyBaseGet200ResponseData.Input);

            if (v1TechnologyBaseGet200ResponseData.FromOption.IsSet)
                writer.WriteNumber("from", v1TechnologyBaseGet200ResponseData.FromOption.Value!.Value);

            if (v1TechnologyBaseGet200ResponseData.ToOption.IsSet)
                writer.WriteNumber("to", v1TechnologyBaseGet200ResponseData.ToOption.Value!.Value);

            if (v1TechnologyBaseGet200ResponseData.ResultOption.IsSet)
                writer.WriteString("result", v1TechnologyBaseGet200ResponseData.Result);
        }
    }
}
