/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing V1FinanceIbanIbanGet200ResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1FinanceIbanIbanGet200ResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1FinanceIbanIbanGet200ResponseData
        //private V1FinanceIbanIbanGet200ResponseData instance;

        public V1FinanceIbanIbanGet200ResponseDataTests()
        {
            // TODO uncomment below to create an instance of V1FinanceIbanIbanGet200ResponseData
            //instance = new V1FinanceIbanIbanGet200ResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1FinanceIbanIbanGet200ResponseData
        /// </summary>
        [Fact]
        public void V1FinanceIbanIbanGet200ResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1FinanceIbanIbanGet200ResponseData
            //Assert.IsType<V1FinanceIbanIbanGet200ResponseData>(instance);
        }

        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Fact]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }

        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Fact]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'BankCode'
        /// </summary>
        [Fact]
        public void BankCodeTest()
        {
            // TODO unit test for the property 'BankCode'
        }

        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
    }
}
