/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// V1EntertainmentEmojiRandomGet200ResponseData
    /// </summary>
    [DataContract(Name = "_v1_entertainment_emoji_random_get_200_response_data")]
    public partial class V1EntertainmentEmojiRandomGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1EntertainmentEmojiRandomGet200ResponseData" /> class.
        /// </summary>
        /// <param name="emoji">The rendered emoji glyph.</param>
        /// <param name="name">CLDR short name in snake_case (e.g. grinning_face).</param>
        /// <param name="category">Unicode category (e.g. Smileys &amp; Emotion, Animals &amp; Nature).</param>
        /// <param name="unicode">Unicode code-point in U+XXXX notation (e.g. U+1F600).</param>
        public V1EntertainmentEmojiRandomGet200ResponseData(string emoji = default, string name = default, string category = default, string unicode = default)
        {
            this.Emoji = emoji;
            this.Name = name;
            this.Category = category;
            this.Unicode = unicode;
        }

        /// <summary>
        /// The rendered emoji glyph
        /// </summary>
        /// <value>The rendered emoji glyph</value>
        [DataMember(Name = "emoji", EmitDefaultValue = false)]
        public string Emoji { get; set; }

        /// <summary>
        /// CLDR short name in snake_case (e.g. grinning_face)
        /// </summary>
        /// <value>CLDR short name in snake_case (e.g. grinning_face)</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Unicode category (e.g. Smileys &amp; Emotion, Animals &amp; Nature)
        /// </summary>
        /// <value>Unicode category (e.g. Smileys &amp; Emotion, Animals &amp; Nature)</value>
        [DataMember(Name = "category", EmitDefaultValue = false)]
        public string Category { get; set; }

        /// <summary>
        /// Unicode code-point in U+XXXX notation (e.g. U+1F600)
        /// </summary>
        /// <value>Unicode code-point in U+XXXX notation (e.g. U+1F600)</value>
        [DataMember(Name = "unicode", EmitDefaultValue = false)]
        public string Unicode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1EntertainmentEmojiRandomGet200ResponseData {\n");
            sb.Append("  Emoji: ").Append(Emoji).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Unicode: ").Append(Unicode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
