/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// V1NetworkingIpVpnIpGet200ResponseData
    /// </summary>
    [DataContract(Name = "_v1_networking_ip_vpn__ip__get_200_response_data")]
    public partial class V1NetworkingIpVpnIpGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1NetworkingIpVpnIpGet200ResponseData" /> class.
        /// </summary>
        /// <param name="ip">The analyzed IP address.</param>
        /// <param name="isVpn">True when the IP belongs to a known VPN provider.</param>
        /// <param name="isProxy">True when the IP is a known public or web proxy.</param>
        /// <param name="isTor">True when the IP is a known Tor exit node.</param>
        /// <param name="isHosting">True when the IP belongs to a data-centre or hosting provider (DCH).</param>
        /// <param name="score">Raw threat score (0-9+). Tor contributes 3, VPN or Proxy each contribute 2, Hosting contributes 1.</param>
        /// <param name="threat">Threat level derived from score: 0 &#x3D; None, 1 &#x3D; Low, 2–3 &#x3D; Medium, 4–5 &#x3D; High, 6+ &#x3D; Critical.</param>
        /// <param name="fraudScore">Fraud risk score from 0 (no risk) to 100 (high risk). Available when using IP2Proxy PX5 or higher.</param>
        /// <param name="asnOrg">Organization name owning the Autonomous System containing the IP (e.g. \&quot;DIGITALOCEAN-ASN\&quot;).</param>
        public V1NetworkingIpVpnIpGet200ResponseData(string ip = default, bool isVpn = default, bool isProxy = default, bool isTor = default, bool isHosting = default, int score = default, int threat = default, int fraudScore = default, string asnOrg = default)
        {
            this.Ip = ip;
            this.IsVpn = isVpn;
            this.IsProxy = isProxy;
            this.IsTor = isTor;
            this.IsHosting = isHosting;
            this.Score = score;
            this.Threat = threat;
            this.FraudScore = fraudScore;
            this.AsnOrg = asnOrg;
        }

        /// <summary>
        /// The analyzed IP address
        /// </summary>
        /// <value>The analyzed IP address</value>
        [DataMember(Name = "ip", EmitDefaultValue = false)]
        public string Ip { get; set; }

        /// <summary>
        /// True when the IP belongs to a known VPN provider
        /// </summary>
        /// <value>True when the IP belongs to a known VPN provider</value>
        [DataMember(Name = "is_vpn", EmitDefaultValue = true)]
        public bool IsVpn { get; set; }

        /// <summary>
        /// True when the IP is a known public or web proxy
        /// </summary>
        /// <value>True when the IP is a known public or web proxy</value>
        [DataMember(Name = "is_proxy", EmitDefaultValue = true)]
        public bool IsProxy { get; set; }

        /// <summary>
        /// True when the IP is a known Tor exit node
        /// </summary>
        /// <value>True when the IP is a known Tor exit node</value>
        [DataMember(Name = "is_tor", EmitDefaultValue = true)]
        public bool IsTor { get; set; }

        /// <summary>
        /// True when the IP belongs to a data-centre or hosting provider (DCH)
        /// </summary>
        /// <value>True when the IP belongs to a data-centre or hosting provider (DCH)</value>
        [DataMember(Name = "is_hosting", EmitDefaultValue = true)]
        public bool IsHosting { get; set; }

        /// <summary>
        /// Raw threat score (0-9+). Tor contributes 3, VPN or Proxy each contribute 2, Hosting contributes 1
        /// </summary>
        /// <value>Raw threat score (0-9+). Tor contributes 3, VPN or Proxy each contribute 2, Hosting contributes 1</value>
        [DataMember(Name = "score", EmitDefaultValue = false)]
        public int Score { get; set; }

        /// <summary>
        /// Threat level derived from score: 0 &#x3D; None, 1 &#x3D; Low, 2–3 &#x3D; Medium, 4–5 &#x3D; High, 6+ &#x3D; Critical
        /// </summary>
        /// <value>Threat level derived from score: 0 &#x3D; None, 1 &#x3D; Low, 2–3 &#x3D; Medium, 4–5 &#x3D; High, 6+ &#x3D; Critical</value>
        [DataMember(Name = "threat", EmitDefaultValue = false)]
        public int Threat { get; set; }

        /// <summary>
        /// Fraud risk score from 0 (no risk) to 100 (high risk). Available when using IP2Proxy PX5 or higher
        /// </summary>
        /// <value>Fraud risk score from 0 (no risk) to 100 (high risk). Available when using IP2Proxy PX5 or higher</value>
        [DataMember(Name = "fraud_score", EmitDefaultValue = false)]
        public int FraudScore { get; set; }

        /// <summary>
        /// Organization name owning the Autonomous System containing the IP (e.g. \&quot;DIGITALOCEAN-ASN\&quot;)
        /// </summary>
        /// <value>Organization name owning the Autonomous System containing the IP (e.g. \&quot;DIGITALOCEAN-ASN\&quot;)</value>
        [DataMember(Name = "asn_org", EmitDefaultValue = false)]
        public string AsnOrg { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1NetworkingIpVpnIpGet200ResponseData {\n");
            sb.Append("  Ip: ").Append(Ip).Append("\n");
            sb.Append("  IsVpn: ").Append(IsVpn).Append("\n");
            sb.Append("  IsProxy: ").Append(IsProxy).Append("\n");
            sb.Append("  IsTor: ").Append(IsTor).Append("\n");
            sb.Append("  IsHosting: ").Append(IsHosting).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("  Threat: ").Append(Threat).Append("\n");
            sb.Append("  FraudScore: ").Append(FraudScore).Append("\n");
            sb.Append("  AsnOrg: ").Append(AsnOrg).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
