/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// V1NetworkingDisposableDomainDomainGet200ResponseData
    /// </summary>
    [DataContract(Name = "_v1_networking_disposable_domain__domain__get_200_response_data")]
    public partial class V1NetworkingDisposableDomainDomainGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1NetworkingDisposableDomainDomainGet200ResponseData" /> class.
        /// </summary>
        /// <param name="domain">The domain that was checked.</param>
        /// <param name="isDisposable">Whether the domain is in the disposable blocklist.</param>
        public V1NetworkingDisposableDomainDomainGet200ResponseData(string domain = default, bool isDisposable = default)
        {
            this.Domain = domain;
            this.IsDisposable = isDisposable;
        }

        /// <summary>
        /// The domain that was checked
        /// </summary>
        /// <value>The domain that was checked</value>
        [DataMember(Name = "domain", EmitDefaultValue = false)]
        public string Domain { get; set; }

        /// <summary>
        /// Whether the domain is in the disposable blocklist
        /// </summary>
        /// <value>Whether the domain is in the disposable blocklist</value>
        [DataMember(Name = "is_disposable", EmitDefaultValue = true)]
        public bool IsDisposable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1NetworkingDisposableDomainDomainGet200ResponseData {\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  IsDisposable: ").Append(IsDisposable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
