/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// V1PlacesGeocodeGet200ResponseData
    /// </summary>
    [DataContract(Name = "_v1_places_geocode_get_200_response_data")]
    public partial class V1PlacesGeocodeGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1PlacesGeocodeGet200ResponseData" /> class.
        /// </summary>
        /// <param name="address">Full display name of the matched location.</param>
        /// <param name="city">City or town of the matched location.</param>
        /// <param name="country">ISO 3166-1 alpha-2 country code (uppercase).</param>
        /// <param name="lat">Latitude of the matched location.</param>
        /// <param name="lon">Longitude of the matched location.</param>
        public V1PlacesGeocodeGet200ResponseData(string address = default, string city = default, string country = default, decimal lat = default, decimal lon = default)
        {
            this.Address = address;
            this.City = city;
            this.Country = country;
            this.Lat = lat;
            this.Lon = lon;
        }

        /// <summary>
        /// Full display name of the matched location
        /// </summary>
        /// <value>Full display name of the matched location</value>
        [DataMember(Name = "address", EmitDefaultValue = false)]
        public string Address { get; set; }

        /// <summary>
        /// City or town of the matched location
        /// </summary>
        /// <value>City or town of the matched location</value>
        [DataMember(Name = "city", EmitDefaultValue = false)]
        public string City { get; set; }

        /// <summary>
        /// ISO 3166-1 alpha-2 country code (uppercase)
        /// </summary>
        /// <value>ISO 3166-1 alpha-2 country code (uppercase)</value>
        [DataMember(Name = "country", EmitDefaultValue = false)]
        public string Country { get; set; }

        /// <summary>
        /// Latitude of the matched location
        /// </summary>
        /// <value>Latitude of the matched location</value>
        [DataMember(Name = "lat", EmitDefaultValue = false)]
        public decimal Lat { get; set; }

        /// <summary>
        /// Longitude of the matched location
        /// </summary>
        /// <value>Longitude of the matched location</value>
        [DataMember(Name = "lon", EmitDefaultValue = false)]
        public decimal Lon { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1PlacesGeocodeGet200ResponseData {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  City: ").Append(City).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Lat: ").Append(Lat).Append("\n");
            sb.Append("  Lon: ").Append(Lon).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
