/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// V1PlacesHolidaysBatchPost200ResponseData
    /// </summary>
    [DataContract(Name = "_v1_places_holidays_batch_post_200_response_data")]
    public partial class V1PlacesHolidaysBatchPost200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1PlacesHolidaysBatchPost200ResponseData" /> class.
        /// </summary>
        /// <param name="results">One result per query, in the same order as the request.</param>
        /// <param name="resultsCountry">ISO 3166-1 alpha-2 country code.</param>
        /// <param name="resultsYear">Year queried.</param>
        /// <param name="resultsFound">false when no holidays exist for that country/year combination.</param>
        /// <param name="resultsHolidays">List of holidays. Omitted when found is false..</param>
        /// <param name="resultsTotal">Number of holidays. Omitted when found is false..</param>
        /// <param name="total">Total number of results (equals the number of queries sent).</param>
        public V1PlacesHolidaysBatchPost200ResponseData(List<Object> results = default, string resultsCountry = default, int resultsYear = default, bool resultsFound = default, List<Object> resultsHolidays = default, int resultsTotal = default, int total = default)
        {
            this.Results = results;
            this.ResultsCountry = resultsCountry;
            this.ResultsYear = resultsYear;
            this.ResultsFound = resultsFound;
            this.ResultsHolidays = resultsHolidays;
            this.ResultsTotal = resultsTotal;
            this.Total = total;
        }

        /// <summary>
        /// One result per query, in the same order as the request
        /// </summary>
        /// <value>One result per query, in the same order as the request</value>
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<Object> Results { get; set; }

        /// <summary>
        /// ISO 3166-1 alpha-2 country code
        /// </summary>
        /// <value>ISO 3166-1 alpha-2 country code</value>
        [DataMember(Name = "results[].country", EmitDefaultValue = false)]
        public string ResultsCountry { get; set; }

        /// <summary>
        /// Year queried
        /// </summary>
        /// <value>Year queried</value>
        [DataMember(Name = "results[].year", EmitDefaultValue = false)]
        public int ResultsYear { get; set; }

        /// <summary>
        /// false when no holidays exist for that country/year combination
        /// </summary>
        /// <value>false when no holidays exist for that country/year combination</value>
        [DataMember(Name = "results[].found", EmitDefaultValue = true)]
        public bool ResultsFound { get; set; }

        /// <summary>
        /// List of holidays. Omitted when found is false.
        /// </summary>
        /// <value>List of holidays. Omitted when found is false.</value>
        [DataMember(Name = "results[].holidays", EmitDefaultValue = false)]
        public List<Object> ResultsHolidays { get; set; }

        /// <summary>
        /// Number of holidays. Omitted when found is false.
        /// </summary>
        /// <value>Number of holidays. Omitted when found is false.</value>
        [DataMember(Name = "results[].total", EmitDefaultValue = false)]
        public int ResultsTotal { get; set; }

        /// <summary>
        /// Total number of results (equals the number of queries sent)
        /// </summary>
        /// <value>Total number of results (equals the number of queries sent)</value>
        [DataMember(Name = "total", EmitDefaultValue = false)]
        public int Total { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1PlacesHolidaysBatchPost200ResponseData {\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("  ResultsCountry: ").Append(ResultsCountry).Append("\n");
            sb.Append("  ResultsYear: ").Append(ResultsYear).Append("\n");
            sb.Append("  ResultsFound: ").Append(ResultsFound).Append("\n");
            sb.Append("  ResultsHolidays: ").Append(ResultsHolidays).Append("\n");
            sb.Append("  ResultsTotal: ").Append(ResultsTotal).Append("\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
