/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// V1TextSimilarityPostRequest
    /// </summary>
    [DataContract(Name = "_v1_text_similarity_post_request")]
    public partial class V1TextSimilarityPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1TextSimilarityPostRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected V1TextSimilarityPostRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V1TextSimilarityPostRequest" /> class.
        /// </summary>
        /// <param name="text1">The first text to compare. (required).</param>
        /// <param name="text2">The second text to compare. (required).</param>
        public V1TextSimilarityPostRequest(string text1 = default, string text2 = default)
        {
            // to ensure "text1" is required (not null)
            if (text1 == null)
            {
                throw new ArgumentNullException("text1 is a required property for V1TextSimilarityPostRequest and cannot be null");
            }
            this.Text1 = text1;
            // to ensure "text2" is required (not null)
            if (text2 == null)
            {
                throw new ArgumentNullException("text2 is a required property for V1TextSimilarityPostRequest and cannot be null");
            }
            this.Text2 = text2;
        }

        /// <summary>
        /// The first text to compare.
        /// </summary>
        /// <value>The first text to compare.</value>
        /*
        <example>The cat sat on the mat</example>
        */
        [DataMember(Name = "text1", IsRequired = true, EmitDefaultValue = true)]
        public string Text1 { get; set; }

        /// <summary>
        /// The second text to compare.
        /// </summary>
        /// <value>The second text to compare.</value>
        /*
        <example>A cat was sitting on a mat</example>
        */
        [DataMember(Name = "text2", IsRequired = true, EmitDefaultValue = true)]
        public string Text2 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1TextSimilarityPostRequest {\n");
            sb.Append("  Text1: ").Append(Text1).Append("\n");
            sb.Append("  Text2: ").Append(Text2).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
