/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// V1TextQuotesRandomGet200ResponseData
    /// </summary>
    [DataContract(Name = "_v1_text_quotes_random_get_200_response_data")]
    public partial class V1TextQuotesRandomGet200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1TextQuotesRandomGet200ResponseData" /> class.
        /// </summary>
        /// <param name="id">Unique identifier for the quote.</param>
        /// <param name="text">The quote text.</param>
        /// <param name="author">Name of the person who said or wrote the quote.</param>
        public V1TextQuotesRandomGet200ResponseData(int id = default, string text = default, string author = default)
        {
            this.Id = id;
            this.Text = text;
            this.Author = author;
        }

        /// <summary>
        /// Unique identifier for the quote
        /// </summary>
        /// <value>Unique identifier for the quote</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// The quote text
        /// </summary>
        /// <value>The quote text</value>
        [DataMember(Name = "text", EmitDefaultValue = false)]
        public string Text { get; set; }

        /// <summary>
        /// Name of the person who said or wrote the quote
        /// </summary>
        /// <value>Name of the person who said or wrote the quote</value>
        [DataMember(Name = "author", EmitDefaultValue = false)]
        public string Author { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1TextQuotesRandomGet200ResponseData {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Author: ").Append(Author).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
