/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Org.OpenAPITools.Client.FileParameter;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// V1ValidationEmailBatchPostRequest
    /// </summary>
    [DataContract(Name = "_v1_validation_email_batch_post_request")]
    public partial class V1ValidationEmailBatchPostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1ValidationEmailBatchPostRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected V1ValidationEmailBatchPostRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V1ValidationEmailBatchPostRequest" /> class.
        /// </summary>
        /// <param name="emails">Array of email addresses to validate. Min: 1, Max: 50. (required).</param>
        public V1ValidationEmailBatchPostRequest(List<Object> emails = default)
        {
            // to ensure "emails" is required (not null)
            if (emails == null)
            {
                throw new ArgumentNullException("emails is a required property for V1ValidationEmailBatchPostRequest and cannot be null");
            }
            this.Emails = emails;
        }

        /// <summary>
        /// Array of email addresses to validate. Min: 1, Max: 50.
        /// </summary>
        /// <value>Array of email addresses to validate. Min: 1, Max: 50.</value>
        /*
        <example>[&quot;user@gmail.com&quot;, &quot;user@gmial.com&quot;]</example>
        */
        [DataMember(Name = "emails", IsRequired = true, EmitDefaultValue = true)]
        public List<Object> Emails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1ValidationEmailBatchPostRequest {\n");
            sb.Append("  Emails: ").Append(Emails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
