/**
 * Generated by orval v8.12.2 🍺
 * Do not edit manually.
 * Requiems API
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 * OpenAPI spec version: 1.0.0
 */
import type { GetV1NetworkingMxDomain200Data } from './getV1NetworkingMxDomain200Data';
import type { GetV1NetworkingMxDomain200Metadata } from './getV1NetworkingMxDomain200Metadata';

export type GetV1NetworkingMxDomain200 = {
  data?: GetV1NetworkingMxDomain200Data;
  metadata?: GetV1NetworkingMxDomain200Metadata;
};
