/**
 * Generated by orval v8.12.2 🍺
 * Do not edit manually.
 * Requiems API
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 * OpenAPI spec version: 1.0.0
 */
import type { GetV1NetworkingDisposableDomainDomain200Data } from './getV1NetworkingDisposableDomainDomain200Data';
import type { GetV1NetworkingDisposableDomainDomain200Metadata } from './getV1NetworkingDisposableDomainDomain200Metadata';

export type GetV1NetworkingDisposableDomainDomain200 = {
  data?: GetV1NetworkingDisposableDomainDomain200Data;
  metadata?: GetV1NetworkingDisposableDomainDomain200Metadata;
};
