/**
 * Generated by orval v8.12.2 🍺
 * Do not edit manually.
 * Requiems API
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 * OpenAPI spec version: 1.0.0
 */

export type GetV1TechnologyRandomUser200Data = {
  /** Full name of the generated user */
  name?: string;
  /** Email address of the generated user */
  email?: string;
  /** Phone number of the generated user */
  phone?: string;
  /** Street address */
  'address.street'?: string;
  /** City name */
  'address.city'?: string;
  /** State or region */
  'address.state'?: string;
  /** Postal / ZIP code */
  'address.zip'?: string;
  /** Country name */
  'address.country'?: string;
  /** URL to a unique identicon avatar for the generated user (DiceBear) */
  avatar?: string;
};
