/**
 * Generated by orval v8.12.2 🍺
 * Do not edit manually.
 * Requiems API
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 * OpenAPI spec version: 1.0.0
 */

export type GetV1PlacesReverseGeocode200Data = {
  /** Latitude as provided in the request */
  lat?: number;
  /** Longitude as provided in the request */
  lon?: number;
  /** Full display name of the location at the given coordinates */
  address?: string;
  /** City or town at the given coordinates */
  city?: string;
  /** ISO 3166-1 alpha-2 country code (uppercase) */
  country?: string;
};
