/**
 * Generated by orval v8.12.2 🍺
 * Do not edit manually.
 * Requiems API
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 * OpenAPI spec version: 1.0.0
 */

export type GetV1NetworkingIpAsn200Data = {
  /** The IP address that was looked up (the requesting client's IP) */
  ip?: string;
  /** Autonomous System Number in format "ASxxxx" (e.g., "AS15169") */
  asn?: string;
  /** Organization name owning the IP address range */
  org?: string;
  /** Internet Service Provider providing the IP */
  isp?: string;
  /** Domain name associated with the IP or IP range */
  domain?: string;
  /** CIDR notation of the network route (e.g., "8.8.8.0/24") */
  route?: string;
  /** Type of network (e.g., "hosting", "isp", "business", "cdn") */
  type?: string;
};
