/**
 * Generated by orval v8.12.2 🍺
 * Do not edit manually.
 * Requiems API
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 * OpenAPI spec version: 1.0.0
 */

export type PostV1ValidationEmail200Data = {
  /** The email address exactly as supplied in the request body; null when syntax is invalid */
  email?: string;
  /** Overall validity. True only when the address passes syntax validation and the domain has at least one MX record */
  valid?: boolean;
  /** Whether the address is syntactically valid according to RFC 5322 */
  syntax_valid?: boolean;
  /** Whether the domain has at least one MX record, meaning it can receive email */
  mx_valid?: boolean;
  /** Whether the address uses a known disposable or temporary email domain */
  disposable?: boolean;
  /** The canonical form of the address after normalization (lowercase, plus-tag removal, alias-domain resolution). Null when syntax is invalid */
  normalized?: string;
  /** The domain part of the address (after @). Null when syntax is invalid */
  domain?: string;
  /** A corrected domain name when the supplied domain looks like a typo of a well-known provider (e.g. gmial.com → gmail.com). Null when no close match is found or the domain is already correct */
  suggestion?: string;
};
