/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithNameGetResponse_data}
 */
// @ts-ignore
export function createWithNameGetResponse_dataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithNameGetResponse_data;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithNameGetResponse_metadata}
 */
// @ts-ignore
export function createWithNameGetResponse_metadataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithNameGetResponse_metadata;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WithNameGetResponse}
 */
// @ts-ignore
export function createWithNameGetResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWithNameGetResponse;
}
/**
 * The deserialization information for the current model
 * @param WithNameGetResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithNameGetResponse(withNameGetResponse: Partial<WithNameGetResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { withNameGetResponse.data = n.getObjectValue<WithNameGetResponse_data>(createWithNameGetResponse_dataFromDiscriminatorValue); },
        "metadata": n => { withNameGetResponse.metadata = n.getObjectValue<WithNameGetResponse_metadata>(createWithNameGetResponse_metadataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param WithNameGetResponse_data The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithNameGetResponse_data(withNameGetResponse_data: Partial<WithNameGetResponse_data> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "category": n => { withNameGetResponse_data.category = n.getStringValue(); },
        "emoji": n => { withNameGetResponse_data.emoji = n.getStringValue(); },
        "name": n => { withNameGetResponse_data.name = n.getStringValue(); },
        "unicode": n => { withNameGetResponse_data.unicode = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param WithNameGetResponse_metadata The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWithNameGetResponse_metadata(withNameGetResponse_metadata: Partial<WithNameGetResponse_metadata> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "timestamp": n => { withNameGetResponse_metadata.timestamp = n.getDateValue(); },
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithNameGetResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithNameGetResponse(writer: SerializationWriter, withNameGetResponse: Partial<WithNameGetResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withNameGetResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<WithNameGetResponse_data>("data", withNameGetResponse.data, serializeWithNameGetResponse_data);
    writer.writeObjectValue<WithNameGetResponse_metadata>("metadata", withNameGetResponse.metadata, serializeWithNameGetResponse_metadata);
    writer.writeAdditionalData(withNameGetResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithNameGetResponse_data The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithNameGetResponse_data(writer: SerializationWriter, withNameGetResponse_data: Partial<WithNameGetResponse_data> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withNameGetResponse_data || isSerializingDerivedType) { return; }
    writer.writeStringValue("category", withNameGetResponse_data.category);
    writer.writeStringValue("emoji", withNameGetResponse_data.emoji);
    writer.writeStringValue("name", withNameGetResponse_data.name);
    writer.writeStringValue("unicode", withNameGetResponse_data.unicode);
    writer.writeAdditionalData(withNameGetResponse_data.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WithNameGetResponse_metadata The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWithNameGetResponse_metadata(writer: SerializationWriter, withNameGetResponse_metadata: Partial<WithNameGetResponse_metadata> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!withNameGetResponse_metadata || isSerializingDerivedType) { return; }
    writer.writeDateValue("timestamp", withNameGetResponse_metadata.timestamp);
    writer.writeAdditionalData(withNameGetResponse_metadata.additionalData);
}
export interface WithNameGetResponse extends AdditionalDataHolder, Parsable {
    /**
     * The data property
     */
    data?: WithNameGetResponse_data | null;
    /**
     * The metadata property
     */
    metadata?: WithNameGetResponse_metadata | null;
}
export interface WithNameGetResponse_data extends AdditionalDataHolder, Parsable {
    /**
     * Unicode category
     */
    category?: string | null;
    /**
     * The rendered emoji glyph
     */
    emoji?: string | null;
    /**
     * CLDR short name in snake_case
     */
    name?: string | null;
    /**
     * Unicode code-point in U+XXXX notation
     */
    unicode?: string | null;
}
export interface WithNameGetResponse_metadata extends AdditionalDataHolder, Parsable {
    /**
     * The timestamp property
     */
    timestamp?: Date | null;
}
/**
 * Builds and executes requests for operations under /v1/entertainment/emoji/{name}
 */
export interface WithNameItemRequestBuilder extends BaseRequestBuilder<WithNameItemRequestBuilder> {
    /**
     * Returns a specific emoji by its CLDR snake_case name. The name is case-insensitive.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WithNameGetResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WithNameGetResponse | undefined>;
    /**
     * Returns a specific emoji by its CLDR snake_case name. The name is case-insensitive.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithNameItemRequestBuilderUriTemplate = "{+baseurl}/v1/entertainment/emoji/{name}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithNameItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithNameItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createWithNameGetResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
