/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { BatchRequestBuilderRequestsMetadata, type BatchRequestBuilder } from './batch/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EmailPostRequestBody}
 */
// @ts-ignore
export function createEmailPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEmailPostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EmailPostResponse_data}
 */
// @ts-ignore
export function createEmailPostResponse_dataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEmailPostResponse_data;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EmailPostResponse_metadata}
 */
// @ts-ignore
export function createEmailPostResponse_metadataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEmailPostResponse_metadata;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {EmailPostResponse}
 */
// @ts-ignore
export function createEmailPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoEmailPostResponse;
}
/**
 * The deserialization information for the current model
 * @param EmailPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEmailPostRequestBody(emailPostRequestBody: Partial<EmailPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { emailPostRequestBody.email = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EmailPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEmailPostResponse(emailPostResponse: Partial<EmailPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { emailPostResponse.data = n.getObjectValue<EmailPostResponse_data>(createEmailPostResponse_dataFromDiscriminatorValue); },
        "metadata": n => { emailPostResponse.metadata = n.getObjectValue<EmailPostResponse_metadata>(createEmailPostResponse_metadataFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param EmailPostResponse_data The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEmailPostResponse_data(emailPostResponse_data: Partial<EmailPostResponse_data> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "disposable": n => { emailPostResponse_data.disposable = n.getBooleanValue(); },
        "domain": n => { emailPostResponse_data.domain = n.getStringValue(); },
        "email": n => { emailPostResponse_data.email = n.getStringValue(); },
        "mx_valid": n => { emailPostResponse_data.mxValid = n.getBooleanValue(); },
        "normalized": n => { emailPostResponse_data.normalized = n.getStringValue(); },
        "suggestion": n => { emailPostResponse_data.suggestion = n.getStringValue(); },
        "syntax_valid": n => { emailPostResponse_data.syntaxValid = n.getBooleanValue(); },
        "valid": n => { emailPostResponse_data.valid = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param EmailPostResponse_metadata The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoEmailPostResponse_metadata(emailPostResponse_metadata: Partial<EmailPostResponse_metadata> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "timestamp": n => { emailPostResponse_metadata.timestamp = n.getDateValue(); },
    }
}
export interface EmailPostRequestBody extends AdditionalDataHolder, Parsable {
    /**
     * The email address to validate.
     */
    email?: string | null;
}
export interface EmailPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * The data property
     */
    data?: EmailPostResponse_data | null;
    /**
     * The metadata property
     */
    metadata?: EmailPostResponse_metadata | null;
}
export interface EmailPostResponse_data extends AdditionalDataHolder, Parsable {
    /**
     * Whether the address uses a known disposable or temporary email domain
     */
    disposable?: boolean | null;
    /**
     * The domain part of the address (after @). Null when syntax is invalid
     */
    domain?: string | null;
    /**
     * The email address exactly as supplied in the request body; null when syntax is invalid
     */
    email?: string | null;
    /**
     * Whether the domain has at least one MX record, meaning it can receive email
     */
    mxValid?: boolean | null;
    /**
     * The canonical form of the address after normalization (lowercase, plus-tag removal, alias-domain resolution). Null when syntax is invalid
     */
    normalized?: string | null;
    /**
     * A corrected domain name when the supplied domain looks like a typo of a well-known provider (e.g. gmial.com → gmail.com). Null when no close match is found or the domain is already correct
     */
    suggestion?: string | null;
    /**
     * Whether the address is syntactically valid according to RFC 5322
     */
    syntaxValid?: boolean | null;
    /**
     * Overall validity. True only when the address passes syntax validation and the domain has at least one MX record
     */
    valid?: boolean | null;
}
export interface EmailPostResponse_metadata extends AdditionalDataHolder, Parsable {
    /**
     * The timestamp property
     */
    timestamp?: Date | null;
}
/**
 * Builds and executes requests for operations under /v1/validation/email
 */
export interface EmailRequestBuilder extends BaseRequestBuilder<EmailRequestBuilder> {
    /**
     * The batch property
     */
    get batch(): BatchRequestBuilder;
    /**
     * Validates a single email address and returns a full breakdown of syntax validity, MX record status, disposable domain check, normalized form, and any typo suggestion.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EmailPostResponse>}
     */
     post(body: EmailPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EmailPostResponse | undefined>;
    /**
     * Validates a single email address and returns a full breakdown of syntax validity, MX record status, disposable domain check, normalized form, and any typo suggestion.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: EmailPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param EmailPostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEmailPostRequestBody(writer: SerializationWriter, emailPostRequestBody: Partial<EmailPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!emailPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", emailPostRequestBody.email);
    writer.writeAdditionalData(emailPostRequestBody.additionalData);
}
/**
 * Serializes information the current object
 * @param EmailPostResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEmailPostResponse(writer: SerializationWriter, emailPostResponse: Partial<EmailPostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!emailPostResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<EmailPostResponse_data>("data", emailPostResponse.data, serializeEmailPostResponse_data);
    writer.writeObjectValue<EmailPostResponse_metadata>("metadata", emailPostResponse.metadata, serializeEmailPostResponse_metadata);
    writer.writeAdditionalData(emailPostResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param EmailPostResponse_data The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEmailPostResponse_data(writer: SerializationWriter, emailPostResponse_data: Partial<EmailPostResponse_data> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!emailPostResponse_data || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("disposable", emailPostResponse_data.disposable);
    writer.writeStringValue("domain", emailPostResponse_data.domain);
    writer.writeStringValue("email", emailPostResponse_data.email);
    writer.writeBooleanValue("mx_valid", emailPostResponse_data.mxValid);
    writer.writeStringValue("normalized", emailPostResponse_data.normalized);
    writer.writeStringValue("suggestion", emailPostResponse_data.suggestion);
    writer.writeBooleanValue("syntax_valid", emailPostResponse_data.syntaxValid);
    writer.writeBooleanValue("valid", emailPostResponse_data.valid);
    writer.writeAdditionalData(emailPostResponse_data.additionalData);
}
/**
 * Serializes information the current object
 * @param EmailPostResponse_metadata The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeEmailPostResponse_metadata(writer: SerializationWriter, emailPostResponse_metadata: Partial<EmailPostResponse_metadata> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!emailPostResponse_metadata || isSerializingDerivedType) { return; }
    writer.writeDateValue("timestamp", emailPostResponse_metadata.timestamp);
    writer.writeAdditionalData(emailPostResponse_metadata.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const EmailRequestBuilderUriTemplate = "{+baseurl}/v1/validation/email";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EmailRequestBuilderNavigationMetadata: Record<Exclude<keyof EmailRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    batch: {
        requestsMetadata: BatchRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const EmailRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: EmailRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createEmailPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeEmailPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
