// <auto-generated>
/*
 * Requiems API
 *
 * Unified access to enterprise-grade APIs — email validation, text utilities, and more. Authenticate with the `requiems-api-key` header.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net;
using System.IO;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;
using System.Diagnostics.CodeAnalysis;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface ICryptoApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        CryptoApiEvents Events { get; }

        /// <summary>
        /// Get Crypto Price
        /// </summary>
        /// <remarks>
        /// Returns current price data for the given cryptocurrency symbol.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbol">Uppercase ticker symbol (e.g. BTC, ETH, SOL)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1FinanceCryptoSymbolGetApiResponse"/>&gt;</returns>
        Task<IV1FinanceCryptoSymbolGetApiResponse> V1FinanceCryptoSymbolGetAsync(string symbol, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get Crypto Price
        /// </summary>
        /// <remarks>
        /// Returns current price data for the given cryptocurrency symbol.
        /// </remarks>
        /// <param name="symbol">Uppercase ticker symbol (e.g. BTC, ETH, SOL)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1FinanceCryptoSymbolGetApiResponse"/>?&gt;</returns>
        Task<IV1FinanceCryptoSymbolGetApiResponse?> V1FinanceCryptoSymbolGetOrDefaultAsync(string symbol, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IV1FinanceCryptoSymbolGetApiResponse"/>
    /// </summary>
    public interface IV1FinanceCryptoSymbolGetApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Org.OpenAPITools.Model.V1FinanceCryptoSymbolGet200Response?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 422 UnprocessableContent
        /// </summary>
        /// <returns></returns>
        bool IsUnprocessableContent { get; }

        /// <summary>
        /// Returns true if the response is 503 ServiceUnavailable
        /// </summary>
        /// <returns></returns>
        bool IsServiceUnavailable { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class CryptoApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnV1FinanceCryptoSymbolGet;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorV1FinanceCryptoSymbolGet;

        internal void ExecuteOnV1FinanceCryptoSymbolGet(CryptoApi.V1FinanceCryptoSymbolGetApiResponse apiResponse)
        {
            OnV1FinanceCryptoSymbolGet?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorV1FinanceCryptoSymbolGet(Exception exception)
        {
            OnErrorV1FinanceCryptoSymbolGet?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class CryptoApi : ICryptoApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<CryptoApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public CryptoApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="ApiKeyProvider"/>
        /// </summary>
        public TokenProvider<ApiKeyToken> ApiKeyProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="CryptoApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CryptoApi(ILogger<CryptoApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, CryptoApiEvents cryptoApiEvents,
            TokenProvider<ApiKeyToken> apiKeyProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<CryptoApi>();
            HttpClient = httpClient;
            Events = cryptoApiEvents;
            ApiKeyProvider = apiKeyProvider;
        }

        partial void FormatV1FinanceCryptoSymbolGet(ref string symbol);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="symbol"></param>
        /// <returns></returns>
        private void ValidateV1FinanceCryptoSymbolGet(string symbol)
        {
            if (symbol == null)
                throw new ArgumentNullException(nameof(symbol));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="symbol"></param>
        private void AfterV1FinanceCryptoSymbolGetDefaultImplementation(IV1FinanceCryptoSymbolGetApiResponse apiResponseLocalVar, string symbol)
        {
            bool suppressDefaultLog = false;
            AfterV1FinanceCryptoSymbolGet(ref suppressDefaultLog, apiResponseLocalVar, symbol);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {2}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="symbol"></param>
        partial void AfterV1FinanceCryptoSymbolGet(ref bool suppressDefaultLog, IV1FinanceCryptoSymbolGetApiResponse apiResponseLocalVar, string symbol);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="symbol"></param>
        private void OnErrorV1FinanceCryptoSymbolGetDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string symbol)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorV1FinanceCryptoSymbolGet(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, symbol);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="symbol"></param>
        partial void OnErrorV1FinanceCryptoSymbolGet(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string symbol);

        /// <summary>
        /// Get Crypto Price Returns current price data for the given cryptocurrency symbol.
        /// </summary>
        /// <param name="symbol">Uppercase ticker symbol (e.g. BTC, ETH, SOL)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1FinanceCryptoSymbolGetApiResponse"/>&gt;</returns>
        public async Task<IV1FinanceCryptoSymbolGetApiResponse?> V1FinanceCryptoSymbolGetOrDefaultAsync(string symbol, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await V1FinanceCryptoSymbolGetAsync(symbol, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Get Crypto Price Returns current price data for the given cryptocurrency symbol.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="symbol">Uppercase ticker symbol (e.g. BTC, ETH, SOL)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IV1FinanceCryptoSymbolGetApiResponse"/>&gt;</returns>
        public async Task<IV1FinanceCryptoSymbolGetApiResponse> V1FinanceCryptoSymbolGetAsync(string symbol, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateV1FinanceCryptoSymbolGet(symbol);

                FormatV1FinanceCryptoSymbolGet(ref symbol);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/v1/finance/crypto/{symbol}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath.TrimEnd('/'), "/v1/finance/crypto/{symbol}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bsymbol%7D", Uri.EscapeDataString(symbol.ToString()));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    ApiKeyToken apiKeyTokenLocalVar1 = (ApiKeyToken) await ApiKeyProvider.GetAsync("requiems-api-key", cancellationToken).ConfigureAwait(false);
                    tokenBaseLocalVars.Add(apiKeyTokenLocalVar1);
                    apiKeyTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar);

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    IEnumerable<MediaTypeWithQualityHeaderValue> acceptHeaderValuesLocalVar = ClientUtils.SelectHeaderAcceptArray(acceptLocalVars);

                    foreach (var acceptLocalVar in acceptHeaderValuesLocalVar)
                        httpRequestMessageLocalVar.Headers.Accept.Add(acceptLocalVar);

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        ILogger<V1FinanceCryptoSymbolGetApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<V1FinanceCryptoSymbolGetApiResponse>();
                        V1FinanceCryptoSymbolGetApiResponse apiResponseLocalVar;

                        switch ((int)httpResponseMessageLocalVar.StatusCode) {
                            default: {
                                string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
                                apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/v1/finance/crypto/{symbol}", requestedAtLocalVar, _jsonSerializerOptions);

                                break;
                            }
                        }

                        AfterV1FinanceCryptoSymbolGetDefaultImplementation(apiResponseLocalVar, symbol);

                        Events.ExecuteOnV1FinanceCryptoSymbolGet(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorV1FinanceCryptoSymbolGetDefaultImplementation(e, "/v1/finance/crypto/{symbol}", uriBuilderLocalVar.Path, symbol);
                Events.ExecuteOnErrorV1FinanceCryptoSymbolGet(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="V1FinanceCryptoSymbolGetApiResponse"/>
        /// </summary>
        public partial class V1FinanceCryptoSymbolGetApiResponse : Org.OpenAPITools.Client.ApiResponse, IV1FinanceCryptoSymbolGetApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<V1FinanceCryptoSymbolGetApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="V1FinanceCryptoSymbolGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1FinanceCryptoSymbolGetApiResponse(ILogger<V1FinanceCryptoSymbolGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            /// <summary>
            /// The <see cref="V1FinanceCryptoSymbolGetApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="contentStream"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public V1FinanceCryptoSymbolGetApiResponse(ILogger<V1FinanceCryptoSymbolGetApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, System.IO.Stream contentStream, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, contentStream, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Org.OpenAPITools.Model.V1FinanceCryptoSymbolGet200Response? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Org.OpenAPITools.Model.V1FinanceCryptoSymbolGet200Response>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Org.OpenAPITools.Model.V1FinanceCryptoSymbolGet200Response? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 422 UnprocessableContent
            /// </summary>
            /// <returns></returns>
            public bool IsUnprocessableContent => 422 == (int)StatusCode;

            /// <summary>
            /// Returns true if the response is 503 ServiceUnavailable
            /// </summary>
            /// <returns></returns>
            public bool IsServiceUnavailable => 503 == (int)StatusCode;

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
